### ISSUE TITLE
Apache did not update its configuration to support PHP7

### ISSUE THREAD

**Issue by zibbizor** [crazy-max/neard#106]
Hello,

I upgraded all my neard packages to try out some PHP7. I first installed the Apache 2.4.17 package as required and enabled it, then installed the php 7.0.0 package and enabled it. Everything went well according to Neard, but running a phpinfo was still returning PHP 5.3.13.

It turns out my httpd.conf has not been modified by Neard and I had to edit the following

PHPIniDir "${NEARD_LIN_PATH}/bin/php/php5.3.13"
LoadFile "${NEARD_LIN_PATH}/bin/php/php5.3.13/php5ts.dll"
LoadModule php5_module "${NEARD_LIN_PATH}/bin/php/php5.3.13/php5apache2_4.dll"

to

PHPIniDir "${NEARD_LIN_PATH}/bin/php/php7.0.0"
LoadFile "${NEARD_LIN_PATH}/bin/php/php7.0.0/php7ts.dll"
LoadModule php7_module "${NEARD_LIN_PATH}/bin/php/php7.0.0/php7apache2_4.dll"

Not sure if it's an odd glitch but thought I'd report it anyway. Thanks for Neard, it's real help for developing.

**Comment by crazy-max** [comment]
Hi,

I think you have edit manually the neard.conf file with the downloaded releases versions.
You just have to extract the releases, then start Neard and switch version from Neard tray icon to apply settings. The "switch version" process modify the configuration files :

![](https://raw.github.com/crazy-max/neard-bin-php/master/img/switchVersion-20151214.png)

You can have more info on the [neard-bin-php](https://github.com/crazy-max/neard-bin-php) and [neard-bin-apache](https://github.com/crazy-max/neard-bin-php) repository.

And glad to see Neard helps you !

**Comment by zibbizor** [comment]
Hello,

This is specifically what caused me to open this ticket. I had PHP7 successfully selected in Neard's tooltip and I did check the neard.conf file and everything seemed to be fine. I realized something was wrong when PHP did not understand short arrays [] and a phpinfo revealed I was still using 5.3.

I was only able to fix it through a manual edit of httpd.conf despite several neard restarts.

**Comment by crazy-max** [comment]
Ok,

Do you follow these steps ? :

#### If Neard not installed
* Download and extract Neard
* Download and extract Apache 2.4.17
* Download and extract PHP 7.0.0
* Start Neard
* Switch to Apache 2.4.17 from Neard tray
* Restart Neard
* Switch to PHP 7.0.0 from Neard tray
* Restart Neard

#### If Neard already installed
* Stop Neard
* Download and extract Apache 2.4.17
* Download and extract PHP 7.0.0
* Start Neard
* Switch to Apache 2.4.17 from Neard tray
* Restart Neard
* Switch to PHP 7.0.0 from Neard tray
* Restart Neard

**Comment by crazy-max** [comment]
Up @zibbizor ?
