### ISSUE TITLE
phpmyadmin export function will not work due to outdated package

### ISSUE THREAD

**Issue by zibbizor** [crazy-max/neard#107]
Hello,

If you are running Neard with:

- Apache 2.4.17
- MariaDB 10.1.9
- PHP 7.0.0

neard's phpmyadmin export function will not work due to the error:
`Fatal error: Cannot 'break' 2 levels in phpmyadmin\phpmyadmin4.0.4\export.php on line 860`

upgrading phpmyadmin to 4.5.3 fix this issue.

**Comment by crazy-max** [comment]
Thanks i will upgrade phpmyadmin for the next release!

**Comment by crazy-max** [comment]
On the next release 3 phpMyAdmin versions will be added to support php5.2 to php7 :
* phpMyAdmin 4.0.10.12 (compatible with PHP 5.2 and MySQL 5)
* phpMyAdmin 4.4.15.2 (compatible with PHP 5.3.7 to 7.0 and MySQL 5.5)
* phpMyAdmin 4.5.3.1 (compatible with PHP 5.5 to 7.0 and MySQL 5.5)
phpmyadmin alias will be switched automatically to the correct version depending on PHP version.

**Comment by crazy-max** [comment]
Solved on Neard 1.0.17
