### ISSUE TITLE
imagick not loading

### ISSUE THREAD

**Issue by Jmos** [crazy-max/neard#109]
![imagick](https://cloud.githubusercontent.com/assets/5389792/12866507/6082ecd8-ccd0-11e5-9c70-50dd96ff15f6.jpg)
may be slash is wrong but i didn't find where I can correct plz help Thank you

**Comment by crazy-max** [comment]
Hi, can you:

* Tell me what is your operating system and platform (eg. Windows 7 64-bits).
* Tell me your Neard version (eg. 1.0.0).

Have you installed Neard Visual C++ redist package ?

**Comment by Jmos** [comment]
Ok problem solved I forget install Vc++ redist Thanks your help

**Comment by crazy-max** [comment]
:+1:
