### ISSUE TITLE
Wrong config in PHP5.6.17 Bundle

### ISSUE THREAD

**Issue by omsi668** [crazy-max/neard#110]
Hello,

The config (neard.conf) file of the php5.6.17r4 bundle is wrong, the PHP version is labelled 5.6.16.

Great software by the way, thanks for the work

**Comment by crazy-max** [comment]
Hello,

Thanks for your feedback :)

**Comment by crazy-max** [comment]
Same problem with PHP 7.0.2 bundle

**Comment by crazy-max** [comment]
Solved on [neard-bin-php r5](https://github.com/crazy-max/neard-bin-php/releases/tag/r5)
