### ISSUE TITLE
PHP7.0.3 selected but not really activated

### ISSUE THREAD

**Issue by dFireGod** [crazy-max/neard#113]
![image](https://cloud.githubusercontent.com/assets/18054791/14040036/1da3098c-f289-11e5-86f0-0bc1da8ea130.png)

also updated the version nums in `neard.conf `file, but no success yet. Also previous error was kind of the latest `neard-apache2.4.17` & latest `neard-php7.0.3` doesn't support each other.

any help is worth more than thanks!

**Comment by dFireGod** [comment]
but php7.0.0 works

**Comment by crazy-max** [comment]
Ok maybe a problem with the PHP 7.0.3 bundle. Can you try the PHP 7.0.2 bundle ?

**Comment by crazy-max** [comment]
I just check bundles `PHP 7.0.3` and `Apache 2.4.17` and i don't have any problems with it.
Can you follow these steps :

* Start Neard
* Switch to PHP 5.3.13 (default) from Neard tray
* Switch to Apache 2.2.22 (default) from Neard tray
* Switch to Apache 2.4.17 from Neard tray
* Switch to PHP 7.0.3 from Neard tray
* Go to http://localhost/?p=phpinfo
