### ISSUE TITLE
Update 1.0.15 -> 1.0.17 Phpmyadmin inaccessible

### ISSUE THREAD

**Issue by berthos** [crazy-max/neard#114]
Bonjour,
J'ai collé via l'explorateur la version complète 1.0.17 dans mon répertoire 1.0.15 et depuis quand je veux accéder à Phpmyadmin j'obtiens une page Index of /phpmyadmin qui liste les fichiers d'un répertoire.
Par contre j'ai toujours le contenu de mon répertoire www.

Quelqu'un peut-il m'aider ? Ai-je utilisé la bonne méthode ?

Question subsidiaire : ai-je aussi perdu mes bases de données ?

(J'ai fait une copie complète avant update ;) )

**Comment by crazy-max** [comment]
Salut berthos!

Alors en effet il y a eu des changements au niveau de phpMyAdmin depuis la version 1.0.16 avec le support de PHP7 et aussi au niveau de la version 1.0.17 avec le support de multiples versions de phpMyAdmin (voir Issue #107) comme tu peux le voir dans le [CHANGELOG.md](https://github.com/crazy-max/neard/blob/master/CHANGELOG.md).

Alors non tu n'as pas perdu des base de données qui se devraient toujours se trouver sous `neard\bin\mysql\mysql5.5.24\data`.

Vu que tu as fait une sauvegarde complète avant l'upgrade je te conseille de repartir sur cette sauvegarde et de suivre les points suivants pour le passage à la version 1.0.17 :
* Remove tccleVersion key in neard.conf
* Change phpmyadminVersion value to 4 in neard.conf
* Remove file neard.exe.manifest
* Remove file neard.exe.rc
* Remove / replace file alias/phpmyadmin.conf
* Remove / replace folder apps/phpmyadmin
* Remove / replace folder core
* Remove / replace folder tools/console
* Remove folder tools/tccle

**Comment by berthos** [comment]
Bonsoir,

Comme je le disais dans mon message, je pars de la version 1.0.15 et non de
la version 1.0.16.
Les changements à faire sont bien ceux cités ci-dessus ?

Cordialement
Stéphane Bertho

Le sam. 2 avr. 2016 à 15:33, Cr@zy <notifications@github.com> a écrit :

> Salut berthos!
>
> Alors en effet il y a eu des changements au niveau de phpMyAdmin depuis la
> version 1.0.16 avec le support de PHP7 et aussi au niveau de la version
> 1.0.17 avec le support de multiples versions de phpMyAdmin (voir Issue
> #107 <https://github.com/crazy-max/neard/issues/107>) comme tu peux le
> voir dans le CHANGELOG.md
> <https://github.com/crazy-max/neard/blob/master/CHANGELOG.md>.
>
> Alors non tu n'as pas perdu des base de données qui se devraient toujours
> se trouver sous neard\bin\mysql\mysql5.5.24\data.
>
> Vu que tu as fait une sauvegarde complète avant l'upgrade je te conseille
> de repartir sur cette sauvegarde et de suivre les points suivants pour le
> passage à la version 1.0.17 :
>
>    - Remove tccleVersion key in neard.conf
>    - Change phpmyadminVersion value to 4 in neard.conf
>    - Remove file neard.exe.manifest
>    - Remove file neard.exe.rc
>    - Remove / replace file alias/phpmyadmin.conf
>    - Remove / replace folder apps/phpmyadmin
>    - Remove / replace folder core
>    - Remove / replace folder tools/console
>    - Remove folder tools/tccle
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/crazy-max/neard/issues/114#issuecomment-204716753>
>
-- 
Cordialement

Stéphane Bertho
Mon CV : http://www.stephane-bertho.fr/
Mon tel : 07 88 19 87 30

**Comment by berthos** [comment]
J'ai fait les modifications demandées et j'obtiens toujours la même chose.

Ci-dessous le fichier neard.conf :
; -- SETTINGS

lang = "english"
timezone = "Europe/Paris"
notepad = "notepad.exe"
maxLogsArchives = "50"
logsVerbose = "2"
scriptsTimeout = "120"

;========================
; No edits necessary beyond this line.
; If you made some changes, you have to reload and/or restart Neard.
;========================

; -- MAIN

defaultLang = "english"
hostname = "bertho-salon"
browser = "C:\Program Files\Internet Explorer\IEXPLORE.EXE"
online = "0"
launchStartup = "0"

; -- BINS

apacheVersion = "2.2.22"

apacheLaunchStartup = "1"

phpVersion = "5.3.13"

mysqlVersion = "5.5.24"
mysqlLaunchStartup = "1"

mariadbVersion = "5.5.34"
mariadbLaunchStartup = "1"

nodejsVersion = "0.12.4"

filezillaVersion = "0.9.47"
filezillaLaunchStartup = "1"


; -- TOOLS

composerVersion = "1.0.0"
consoleVersion = "2.00.148"
gitVersion = "1.8.4"
imagemagickVersion = "6.8.9-7"
runfromprocessVersion = "1.05"
setenvVersion = "1.09"
sublimetextVersion = "3.3059"
svnVersion = "1.7.14"
xdcVersion = "1.0b3"


; -- APPS

adminerVersion = "4.1.0"
gitlistVersion = "0.4.0"
phpmyadminVersion = "4"
webgrindVersion = "1.0"
websvnVersion = "2.3.3"
[image: Clipboard01.jpg]

Le sam. 2 avr. 2016 à 19:23, Stéphane BERTHO <bertho.stephane@gmail.com> a
écrit :

> Bonsoir,
>
> Comme je le disais dans mon message, je pars de la version 1.0.15 et non
> de la version 1.0.16.
> Les changements à faire sont bien ceux cités ci-dessus ?
>
> Cordialement
> Stéphane Bertho
>
> Le sam. 2 avr. 2016 à 15:33, Cr@zy <notifications@github.com> a écrit :
>
>> Salut berthos!
>>
>> Alors en effet il y a eu des changements au niveau de phpMyAdmin depuis
>> la version 1.0.16 avec le support de PHP7 et aussi au niveau de la version
>> 1.0.17 avec le support de multiples versions de phpMyAdmin (voir Issue
>> #107 <https://github.com/crazy-max/neard/issues/107>) comme tu peux le
>> voir dans le CHANGELOG.md
>> <https://github.com/crazy-max/neard/blob/master/CHANGELOG.md>.
>>
>> Alors non tu n'as pas perdu des base de données qui se devraient toujours
>> se trouver sous neard\bin\mysql\mysql5.5.24\data.
>>
>> Vu que tu as fait une sauvegarde complète avant l'upgrade je te conseille
>> de repartir sur cette sauvegarde et de suivre les points suivants pour le
>> passage à la version 1.0.17 :
>>
>>    - Remove tccleVersion key in neard.conf
>>    - Change phpmyadminVersion value to 4 in neard.conf
>>    - Remove file neard.exe.manifest
>>    - Remove file neard.exe.rc
>>    - Remove / replace file alias/phpmyadmin.conf
>>    - Remove / replace folder apps/phpmyadmin
>>    - Remove / replace folder core
>>    - Remove / replace folder tools/console
>>    - Remove folder tools/tccle
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/crazy-max/neard/issues/114#issuecomment-204716753>
>>
> --
> Cordialement
>
> Stéphane Bertho
> Mon CV : http://www.stephane-bertho.fr/
> Mon tel : 07 88 19 87 30
>
-- 
Cordialement

Stéphane Bertho
Mon CV : http://www.stephane-bertho.fr/
Mon tel : 07 88 19 87 30

**Comment by crazy-max** [comment]
Oui les changements à faire sont bien ceux que j'ai cité, peux-tu m'envoyer le contenu du fichier `neard\alias\phpmyadmin.conf` et également suivre les instructions suivantes et les remonter dans ce ticket: [Found a bug?](https://github.com/crazy-max/neard#found-a-bug).

**Comment by berthos** [comment]
Je ne vois pas "les instructions suivantes" dans ce nouveau mel.

Voici le contenu de phpmyadmin.conf (le répertoire existe bien) :
Alias /phpmyadmin "D:/App/web/neard/apps/phpmyadmin/phpmyadmin4/4.4.15.2/"

# to give access to phpmyadmin from outside
# replace the lines
#
#        Order Deny,Allow
# Deny from all
# Allow from 127.0.0.1
#
# by
#
#        Order Allow,Deny
#   Allow from all
#

<Directory "D:/App/web/neard/apps/phpmyadmin/phpmyadmin4/4.4.15.2/">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride all
    # START switchOnline tag - Do not replace!
    Order Deny,Allow
    Deny from all
    Allow from 127.0.0.1 ::1
    # END switchOnline tag - Do not replace!

    php_admin_value upload_max_filesize 128M
    php_admin_value post_max_size 128M
    php_admin_value max_execution_time 360
    php_admin_value max_input_time 360
</Directory>

Le dim. 3 avr. 2016 à 15:10, Cr@zy <notifications@github.com> a écrit :

> Oui les changements à faire sont bien ceux que j'ai cité, peux-tu
> m'envoyer le contenu du fichier neard\alias\phpmyadmin.conf et également
> suivre les instructions suivantes et les remonter dans ce ticket: Found a
> bug? <https://github.com/crazy-max/neard#found-a-bug>.
>
> —
> You are receiving this because you authored the thread.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/crazy-max/neard/issues/114#issuecomment-204970813>
>
-- 
Cordialement

Stéphane Bertho
Mon CV : http://www.stephane-bertho.fr/
Mon tel : 07 88 19 87 30

**Comment by berthos** [comment]
Voici les logs 
[neard_core_tmp.zip](https://github.com/crazy-max/neard/files/201504/neard_core_tmp.zip)

**Comment by crazy-max** [comment]
Les "instruction suivantes" c'était le lien à la fin du message : [Found a bug?](https://github.com/crazy-max/neard#found-a-bug).

Dans les logs il n'y a pas tout, vous m'avez juste envoyé le dossier `core/tmp`, il me faut également le contenu du dossier `logs`.

**Comment by berthos** [comment]
Voici le répertoire logs
[logs.zip](https://github.com/crazy-max/neard/files/206441/logs.zip)

**Comment by crazy-max** [comment]
Neard n'est pas en mode debug au niveau des logs, vous n'avez pas suivi ce point je pense :
* Change the logsVerbose variable to this value 2 in the neard.conf file.

Revoyez les points ci-dessous et renvoyez-moi les logs :

> ## Found a bug?
> 
> Please search for existing issues first and make sure to include all relevant information.
> Before [reporting an issue](https://github.com/crazy-max/neard/issues), please :
> * Tell me what is your operating system and platform (eg. Windows 7 64-bits).
> * Tell me your Neard version (eg. 1.0.0).
> * Close Neard.
> * Change the ``logsVerbose`` variable to this value ``2`` in the ``neard.conf`` file.
> * Launch Neard and reproduce your problem.
> * Close Neard.
> * Zip the ``logs`` folder, the ``core/tmp`` folder and a screenshot of your issue.
> * Upload the zip file on a file hosting system like [Sendspace](https://www.sendspace.com/).
> * Add the link of the uploaded file to the issue.

Je voudrais également savoir à partir de quel lien vous avez téléchargé la version 1.0.17.

**Comment by berthos** [comment]
Bonjour,

Si le verbose est bien à 2 :
; -- SETTINGS

lang = "english"
timezone = "Europe/Paris"
notepad = "notepad.exe"
maxLogsArchives = "50"
logsVerbose = "2"
scriptsTimeout = "120"

J'ai téléchargé le 1.0.17 sur GitHub

Le mer. 6 avr. 2016 à 15:12, Cr@zy <notifications@github.com> a écrit :

> Neard n'est pas en mode debug au niveau des logs, vous n'avez pas suivi ce
> point je pense :
>
>    - Change the logsVerbose variable to this value 2 in the neard.conf
>    file.
>
> Revoyez les points ci-dessous et renvoyez-moi les logs :
>
> Found a bug?
>
> Please search for existing issues first and make sure to include all
> relevant information.
> Before reporting an issue <https://github.com/crazy-max/neard/issues>,
> please :
>
>    - Tell me what is your operating system and platform (eg. Windows 7
>    64-bits).
>    - Tell me your Neard version (eg. 1.0.0).
>    - Close Neard.
>    - Change the logsVerbose variable to this value 2 in the neard.conf
>    file.
>    - Launch Neard and reproduce your problem.
>    - Close Neard.
>    - Zip the logs folder, the core/tmp folder and a screenshot of your
>    issue.
>    - Upload the zip file on a file hosting system like Sendspace
>    <https://www.sendspace.com/>.
>    - Add the link of the uploaded file to the issue.
>
> Je voudrais également savoir à partir de quel lien vous avez téléchargé la
> version 1.0.17.
>
> —
> You are receiving this because you authored the thread.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/crazy-max/neard/issues/114#issuecomment-206362690>
>
-- 
Cordialement

Stéphane Bertho
Mon CV : http://www.stephane-bertho.fr/
Mon tel : 07 88 19 87 30

**Comment by crazy-max** [comment]
Ok, pouvez-vous arrêter neard, supprimer le contenu du répertoire logs, exécuter neard, vous rendre sur http://localhost/phpmyadmin, zipper le répertoire logs et me le renvoyer ?

Vous avez utilisé le lien suivant pour le téléchargement : https://github.com/crazy-max/neard/releases/download/v1.0.17/neard-1.0.17.zip ?

**Comment by berthos** [comment]
Voici les nouveaux logs
[logs.zip](https://github.com/crazy-max/neard/files/206634/logs.zip)

**Comment by crazy-max** [comment]
J'ai repéré plusieurs problèmes.

* Erreur executable introuvable dans : `D:/App/web/neard-1.0.17/neard/tools/notepad2/notepad24.2.25/Notepad2.exe`. Vérifiez que le dossier notepad24.2.25 est bien présent le mieux étant de reprendre celui dans le zip de Neard 1.0.17.
* Comme pour le premier point, le répertoire `D:/App/web/neard-1.0.17/neard/bin/nodejs/nodejs0.12.9` est introuvable. Vérifiez que le dossier nodejs0.12.9 est bien présent le mieux étant de reprendre celui dans le zip de Neard 1.0.17.
* Comparez et modifiez votre fichier `neard.conf` avec celui du zip de Neard 1.0.17 car des paramètres n'ont pas été ajustés et remontent des erreurs.
* Des redirections apache sont faites depuis le répertoire `D:/App/web/neard-1.0.17/neard/www/`. Pouvez-vous me lister le contenu de ce répertoire et vérifier qu'il n'existe pas de fichier `.htaccess`.

**Comment by crazy-max** [comment]
Si vous voulez repartir d'une base propre de Neard je vous conseille :
* de remettre votre sauvegarde de la 1.0.15
* exécuter Neard
* exporter vos base de données avec phpMyAdmin
* stopper Neard
* de sauvegarder les répertoires ssl, vhosts, www
* mettre de côté neard.conf
* une fois les bdd et dossiers mis de côté, supprimer tout et dézipper Neard 1.0.17
* comparer et adapter le fichier neard.conf par rapport à votre ancienne installation
* démarrer Neard et vérifier que tout fonctionne

**Comment by berthos** [comment]
Bonjour,

Je suis reparti du zip dont vous m'avez donné le lien.
En relançant en mode debug, j'ai toujours les mêmes erreurs et en regardant dans le zip : 
- il n'y a pas le nodejs0.12.9, il n'y a que le nodejs0.12.4 et le nodejs0.10.22
- il n'y a pas le Notepad2.exe
Je vais essayer de les installer individuellement.

**Comment by berthos** [comment]
Bonjour,

Tout est revenu à la normale. Je suis en version 1.0.17

Merci pour le support et merci pour vos développements sur Neard.

Vous pouvez fermer le ticket

**Comment by crazy-max** [comment]
Ok tant mieux :)

**Comment by crazy-max** [comment]
Je mettrais des instructions plus détaillées pour les  montées en version désormais

**Comment by berthos** [comment]
Merci pour nous

Le jeu. 7 avr. 2016 18:46, Cr@zy <notifications@github.com> a écrit :

> Je mettrais des instructions plus détaillées pour les montées en version
> désormais
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/crazy-max/neard/issues/114#issuecomment-206987914>
>
-- 
Cordialement

Stéphane Bertho
Mon CV : http://www.stephane-bertho.fr/
Mon tel : 07 88 19 87 30
