### ISSUE TITLE
Fichiers conf et ini corrompus lors d'une coupure de courant

### ISSUE THREAD

**Issue by berthos** [crazy-max/neard#115]
Bonjour,
J'ai subi ce matin une coupure de courant alors que j'utilisais neard.
En voulant relancer neard, j'ai eu un message d'errreur sur l'absence de trayicon dans le fichier ini.

En regardant, en fait, le fichier conf et ini étaient remplis de NUL

Heureusement, j'avais une sauvegarde de neard.

Je ne sais pas si ce phénomène est débugable.

**Comment by crazy-max** [comment]
Bonjour,

En effet ça risque d'être compliqué sans logs.
