### ISSUE TITLE
Add aliases doesn't work with quote or accented letters or special letters

### ISSUE THREAD

**Issue by berthos** [crazy-max/neard#116]
Perhaps it would be good to specify that add aliases doesn't work with quote or accented letters or special letters.

There is no warning when I have tried to create the alias "De l'Aleph à l'@" but the file created was : "De l'Aleph Ã  l'"  without the extension.

**Comment by crazy-max** [comment]
Of course an alias must be alphanumeric without special chars.
I will add a warning.

**Comment by crazy-max** [comment]
Solved on Neard 1.0.18
