### ISSUE TITLE
load localhost page regardless of update status

### ISSUE THREAD

**Issue by iansebryk** [crazy-max/neard#135]
whenever an update is available the localhost page doesn't load at all; only the option to download the new update appears.  can i either bypass this or enable the page to continue to load underneath?  i don't upgrade until the scheduled maintenance block so it would be nice to still have the localhost page load underneath the upgrade banner so i can keep my workflow going.  :)

love the software.  love that's it's in active development.  i just need to see my familiar localhost page.  :)

**Comment by crazy-max** [comment]
Can you send me a screenshot of your homepage and your Firebug or Chrome console ?
I just saw a problem retrieving the latest changelog in the logs maybe there is an issue.

**Comment by crazy-max** [comment]
And give me you Apache / PHP version too!

**Comment by iansebryk** [comment]
here you go.  and i'm running Neard 1.0.17 with the version of Apache/PHP that bundle deploys; looks like 2.2.22 and 5.3.13 respectively

[logs.zip](https://github.com/crazy-max/neard/files/249069/logs.zip)
![neard-localhost-at-update](https://cloud.githubusercontent.com/assets/1943574/15019452/51e0e2d4-11db-11e6-9887-194300d39396.JPG)

on a side note, how do i disable the FTP server?  i don't need it.  :)

thank you so much.  i love this package.  :dancers:

**Comment by crazy-max** [comment]
You're welcome ;)

Do you have the `logs/neard-error.log` file for me ?

To disable Filezilla :
* Left Click on tray icon
* Filezilla > Service > Launch on startup

**Comment by iansebryk** [comment]
the link to the logs.zip is just above the image.  it's easy to overlook.  :)  i just zipped the whole 'logs' folder.

**Comment by crazy-max** [comment]
Ok there's effectively a bug.
Will be solved in the next release!

**Comment by crazy-max** [comment]
Solved on Neard 1.0.19
