### ISSUE TITLE
MailHog error with neard-1.0.19

### ISSUE THREAD

**Issue by berthos** [crazy-max/neard#137]
See the attached file
[erreur.zip](https://github.com/crazy-max/neard/files/262780/erreur.zip)

**Comment by crazy-max** [comment]
Do you try to upgrade from a previous release ?
Logs and scripts are mixed up and it's pretty hard to resolve. And there is no neard-startup.log it's strange.
Please read [Reporting an issue Wiki page](https://github.com/crazy-max/neard/wiki/Reporting-an-issue) and give me all informations.

**Comment by berthos** [comment]
I am using the 1.0.18.

**Comment by crazy-max** [comment]
Can you provide new logs like i said because neard-startup is missing.
Thanks
