### ISSUE TITLE
Where is filezilla_admin.bat?

### ISSUE THREAD

**Issue by iansebryk** [crazy-max/neard#138]
i'm wanting to get an FTP server running but i can't find the filezilla_admin.bat file that launches the UI for setting up users and groups.  tough to run a server without those.  :)  can you illuminate plz?  is there a neard way to do it instead?

thank you.  :)

**Comment by Jmos** [comment]
Here admin ui this is 0.9.47 
[FileZilla Server Interface.zip](https://github.com/crazy-max/neard/files/275834/FileZilla.Server.Interface.zip)

**Comment by crazy-max** [comment]
@iansebryk Today Neard does not provide the FileZilla Server Interface. But like @Jmos said you can easily copy/paste the `FileZilla Server Interface.exe` from offical binaries on Filezilla Website.
On the next release i will integrate the admin interface.

**Comment by iansebryk** [comment]
@Jmos, thank you for the handy link!  @crazy-max, you are amazing!  best foundation tool ever.  indispensible now.  thank you.

**Comment by crazy-max** [comment]
On the next release you'll have an Administration button in the Filezilla menu :

![image2](https://cloud.githubusercontent.com/assets/1951866/16284739/f0476ff6-38d2-11e6-8fc1-b8cac22829c7.png)

**Comment by crazy-max** [comment]
Solved on Neard 1.0.20
