### ISSUE TITLE
Problem with core?

### ISSUE THREAD

**Issue by dmccan** [crazy-max/neard#140]
I followed the instruction in reporting an issue, but no log files were created in core/tmp.  

I downloaded the zip file of the master branch an hour ago.  I followed the instructions in the change log for the required items.  I launched neard, but there were no loading progress bars and I could not access localhost.  I removed the 'core' directory that I had copied over and put the old back and neard launched fine.  

I'm able to keep working, so am not anxious, but wanted to mention it in case there was an issue with core.

Best regards

**Comment by crazy-max** [comment]
>I downloaded the zip file of the master branch an hour ago.

The source code of the master branch is not for end user.
You have to download the package (`neard-x.x.x.7z` or `neard-x.x.x.zip`) from [Releases](https://github.com/crazy-max/neard/releases).

**Comment by dmccan** [comment]
Thanks.  Sorry for the churn.
