### ISSUE TITLE
Change start service and stop service menu icons

### ISSUE THREAD

**Issue by thaasch** [crazy-max/neard#141]
The icon start service and stop service are mixed up.

**Comment by crazy-max** [comment]
Hi,

Can you include these information please :
* What is your operating system and platform (eg. Windows 7 64-bits).
* Neard version (eg. 1.0.0) and the previous version in case of upgrade.
* A screenshot of your issue

Thanks

**Comment by thaasch** [comment]
I´m using Windows 10 (64-bits)
Neard 1.0.20
![neard](https://cloud.githubusercontent.com/assets/8377690/16554461/51569f88-41cf-11e6-8f02-ee4cece6cd4e.png)

**Comment by crazy-max** [comment]
Ok thanks

**Comment by crazy-max** [comment]
Solved on Neard 1.0.21
