### ISSUE TITLE
Ioncube Loader

### ISSUE THREAD

**Issue by ciptamedia** [crazy-max/neard#144]
Is possible to add ioncube loader module to Neard?

**Comment by crazy-max** [comment]
Of course

**Comment by crazy-max** [comment]
Steps to add Ioncube Loader inside Neard :
* Download a loader based on your php version : https://www.ioncube.com/loaders.php
  * PHP 5.2 : Windows VC6 (32 bits)
  * PHP 5.3 : Windows VC9 (32 bits)
  * PHP 5.4 : Windows VC9 (32 bits)
  * PHP 5.5 : Windows VC11 (32 bits)
  * PHP 5.6 : Windows VC11 (32 bits)
  * PHP 7.0 : Windows VC14 (32 bits)
* Copy the dll inside your php folder `ioncube_loader_win_x.x.dll` (Replace x.x with your version of PHP eg. 5.3)
* Add a new line in your php.ini with : `zend_extension = C:/neard/bin/php/phpx.x/ioncube_loader_win_x.x.dll`
* Restart apache and go to http://localhost/?p=phpinfo to check ioncube is loaded
