### ISSUE TITLE
Not starting 

### ISSUE THREAD

**Issue by motikarq** [crazy-max/neard#148]
Hey there, 

I have downloaded release.version = 1.0.20
When I try to start it, only the icon appears in the traybar, but no GUI or whatsoever. 
Using Windows 10 x64.

**Comment by crazy-max** [comment]
Hi,

Please read and apply the [Reporting an issue](https://github.com/crazy-max/neard/wiki/Reporting-an-issue) page.

**Comment by coffeemart** [comment]
Same problem neard don´t start. I installed  Neard Visual C++ Redistributables Package. I start neard.exe An icon appears but when the mouse passes over it only shows a message "none of 4 services running" and localhost shows blank page. Thanks if any help available My windows 10/64

**Comment by crazy-max** [comment]
Hi,

What link do you used to download Neard ?

**Comment by coffeemart** [comment]
Hi.. at home page I selected Clone or download button then download the zip file

**Comment by crazy-max** [comment]
"Clone or download" button is to download the sources, not the final package.
You have to go to the [Releases page](https://github.com/crazy-max/neard/releases) and download the zip or 7z file.

**Comment by StaggerLeee** [comment]
I had similar problem and fixed it by installing prerequisites. Happened after one BSOD and sudden restart. Despite I have no clue what BSOD had to do with this (things inside prerequisites), this helped and solved problem.

https://github.com/crazy-max/neard-prerequisites/releases/tag/r7

**Comment by crazy-max** [comment]
@StaggerLeee Now we have a website : http://neard.io :)
