### ISSUE TITLE
Add Perl

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/neard#155]

**Comment by N6REJ** [comment]
absolutely agree pearl should be native.

**Comment by crazy-max** [comment]
Will be on the next release

**Comment by N6REJ** [comment]
Any eta max?

**Comment by crazy-max** [comment]
End of june i think

**Comment by crazy-max** [comment]
Ok i'm just starting working on it

**Comment by crazy-max** [comment]
Done, i will make a new package of Neard
