### ISSUE TITLE
Can't switch PostgreSQL version

### ISSUE THREAD

**Issue by wblondel** [crazy-max/neard#160]
Hi!

I've downloaded PostgreSQL version 9.5.3 and 9.6.0 from here : https://github.com/crazy-max/neard/wiki/binPostgreSQL#releases
When I try to switch version, I get this error : 

> Neard config files not found for PostgreSQL 9.6.0
![2016-11-02_17h25_28](https://cloud.githubusercontent.com/assets/7508531/19937393/6204ab16-a121-11e6-85dc-260dd860d475.png)

I checked in the folder and there is a neard.conf, so I don't understand :/
I'm using Neard 1.0.21 and Windows 10 x64.

Here are the logs and core\tmp folders after I started all services, tried to switch PostgreSQL version and exited Neard :
https://drive.google.com/open?id=0B78RsOK63NwnSFVfWW5TbDlleEU

What could be the problem ?

Thanks

**Comment by crazy-max** [comment]
Hi,

Thanks for your contrib, i think the generation of the data folder failed.
Can you read the [Reporting an issue]( https://github.com/crazy-max/neard/wiki/Reporting-an-issue) and post the logs ?

**Comment by wblondel** [comment]
Hi,
I posted the logs already, there is GDrive link.

**Comment by crazy-max** [comment]
Oh yes thx

**Comment by crazy-max** [comment]
There is a side effect while switching PostgreSQL version.
For the moment as a workaournd, you can do this :
* Close Neard
* Open neard.conf file (root folder)
* Replace `postgresqlVersion = "9.4.8"` with `postgresqlVersion = "9.6.0"`
* Start Neard

**Comment by crazy-max** [comment]
This bug implies MySQL >= 5.7 too
