### ISSUE TITLE
30% CPU usage for 2 minutes while generating SSL certificate

### ISSUE THREAD

**Issue by wblondel** [crazy-max/neard#161]
Hi,

I'm using Neard 1.0.21, Windows 10 x64 and Apache 2.4.23.

When I add a Virtual Host, it takes 2 minutes to complete the process, and during this time the CPU usage is 30%.

Is it the normal behaviour ?

Thanks

**Comment by crazy-max** [comment]
Hi,

Probably due to SSL certificate generation.
Can you read the [Reporting an issue]( https://github.com/crazy-max/neard/wiki/Reporting-an-issue) page and post the logs ?

Thanks

**Comment by crazy-max** [comment]
@wblondel Can you post the logs plz ?

**Comment by crazy-max** [comment]
It's an issue from OpenSSL lib, will be solved on 1.0.22.
