### ISSUE TITLE
"Change root password" doesn't work for PostgreSQL because root user doesn't exist

### ISSUE THREAD

**Issue by wblondel** [crazy-max/neard#162]
Hi,

In the menu of Neard we can change the root password of PostgreSQL.
When we do it it says "Root password changed successfully!", even when no root user exists.
In the logs we can see that it failed.

> FATAL:  role "root" does not exist

Indeed, PostgreSQL does not have a root user by default. It has a `postgres ` user though (see http://serverfault.com/questions/110154/whats-the-default-superuser-username-password-for-postgres-after-a-new-install).

**Comment by crazy-max** [comment]
Yes if you read the FAQ in the wiki, the default root user is postgres with no password
Maybe is there a bug, i will investigate.

**Comment by wblondel** [comment]
Yep, the bug is that Neard tries to change the password of user 'root' instead of 'postgres'

**Comment by crazy-max** [comment]
Which version of PostgreSQL bundle do you use ?

**Comment by wblondel** [comment]
I use version 9.4.8.
[neard.txt](https://github.com/crazy-max/neard/files/571878/neard.txt)

You can see in the config file that I changed the password to "rrr" with the Neard utility. However Neard tried to change the root user password instead of the postgres user password and failed.

**Comment by crazy-max** [comment]
I've tried to reproduce without success.
Can you post the logs plz ?

**Comment by crazy-max** [comment]
@wblondel Can you post your logs plz? Thx.

**Comment by crazy-max** [comment]
@wblondel ?
