### ISSUE TITLE
Problem: Adminer

### ISSUE THREAD

**Issue by 1959didier** [crazy-max/neard#169]
Hello, I installed Neard 1.0.21, but when I add PHP7.0.11, Adminer 4.2.5 no longer works.
Do you have a solution to my problem?
Here is my problem, With several lines like this :

```
Warning: Declaration of AdminerPlugin::databases() should be compatible with Adminer::databases($Lc = true) in D:\neard1.0.21\apps\adminer\adminer4.2.5\plugins\plugin.php on line 345
```

Thank you

**Comment by crazy-max** [comment]
Hi,

Thanks for your feedback i'll keep you in touch!

**Comment by crazy-max** [comment]
The [plugin.php](https://raw.githubusercontent.com/vrana/adminer/master/plugins/plugin.php) file from Adminer repository was not updated.
Download the file in `neard\apps\adminer\adminer\adminer4.2.5\plugins\`
Will be solved in the next [neard-app-adminer](https://github.com/crazy-max/neard-app-adminer) release (r5).

**Comment by 1959didier** [comment]
I thank you very much
I will have another question is it possible to built-in "Neard" HeidiSQL
Thank you


________________________________
De : Cr@zy <notifications@github.com>
Envoyé : jeudi 24 novembre 2016 18:58
À : crazy-max/neard
Cc : 1959didier; Author
Objet : Re: [crazy-max/neard] Problem: Adminer (#169)


Hi,

Thanks for your feedback i'll keep you in touch!

-

**Comment by crazy-max** [comment]
New release published on [neard-app-adminer](https://github.com/crazy-max/neard-app-adminer/releases/tag/r5)
