### ISSUE TITLE
Windows Script Host Error 80070002 on startup

### ISSUE THREAD

**Issue by iansebryk** [crazy-max/neard#185]
on startup i am getting TWO error popups from neard/core/scripts/execSilent.vbs on line 19 reporting that it cannot find the file specified.

![neardvbscripterror](https://cloud.githubusercontent.com/assets/1943574/20954330/793dd00a-bbf7-11e6-89fb-bfe357cdee50.jpg)

i checked and the file it is looking for is unknown, but the offending line is as follows:

`Return = objShell.Run("""" & args(0) & """" & sargs, 0, True)`

so.  other than being locked out of my PHPMyAdmin (a seemingly regular occurence for reasons i haven't nailed down), everything is running tickety-boo.  i love this package!  :)  thank you so much for all your hard work.

**Comment by crazy-max** [comment]
Hi!

Please read the "Reporting an issue" wiki page.

**Comment by crazy-max** [comment]
@iansebryk Can you posts the logs please or is it solved ?

**Comment by iansebryk** [comment]
sorry.  i was in a time crunch.  i just nuked the whole thing and reinstalled.  :P  upside, it also solved the PHPMyAdmin thing too...  apologies about forgetting to UL the logs.

**Comment by crazy-max** [comment]
No problem thx for your feedback
