### ISSUE TITLE
PHP 7 Curl and OpenSSL cannot be loaded

### ISSUE THREAD

**Issue by myspulin** [crazy-max/neard#199]
Hello,

I have tried to migrate my project to PHP 7 but I get these errors after start PHP ver. 7.1 and 7.0.13

PHP Warning:  PHP Startup: Unable to load dynamic library 'D:/neard/bin/php/php7.1.0/ext\\php_curl.dll' - %1 nelze spustit.\r\n in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'D:/neard/bin/php/php7.1.0/ext\\php_openssl.dll' - %1 nelze spustit.\r\n in Unknown on line 0

So both extensions cannot be loaded, on PHP 5.6.16 it works normally, but does not work for PHP 7.1 and PHP 7.0.13 as well. I get the same errors. My apache version is 1.4.12 on WIN 8.1.

Could you please check this issue? I love this piece of software and use it every day, thank you!

Best regards, Lukas

**Comment by crazy-max** [comment]
Hi @myspulin !

I think this issue is linked to #193
For a quick win you can restart your computer after switching your PHP version or wait for 1.0.22 today ;)
Btw it's Apache 2.4.12 right ?

Regards,

**Comment by myspulin** [comment]
Hi, 

sure, it's of course Apache 2.4.12, thanks for quick answer;-) I can't wait for 1.0.22, thank you!

Regards, Lukas

**Comment by crazy-max** [comment]
Ok,

Can you try restarting your computer and check if it works ?

Thanks

**Comment by myspulin** [comment]
I did a restart but have no luck, get the same issue, errors are all the same:-( Sorry.

**Comment by crazy-max** [comment]
Please read the [Reporting an issue](https://github.com/crazy-max/neard/wiki/Reporting-an-issue) page and post logs.

Thanks

**Comment by myspulin** [comment]
I did some more tests and on Neard v1.0.20 it works normally, the problem is just on my older Neard v1.0.16 installation. So there are probably some binary incompatibility of dll extensions. I will udpate on the latest version, in case you want to go through my logs file after all, let me know, I will upload them somewhere. But I think it is just wasting your time.... Thanks.

**Comment by crazy-max** [comment]
Hum ok so you were on Neard 1.0.16 and upgrade to 1.0.20 but do you follow the [UPGRADE.md](https://github.com/crazy-max/neard/blob/master/UPGRADE.md) ?

I think the best way is to start from a fresh install of the 1.0.22 release and then migrate your projects from `www` and your MySQL and/or MariaDB databases.
Then recreate your vhosts and aliases.

Keep me in touch

Thanks

**Comment by crazy-max** [comment]
@myspulin Any feedback ?

**Comment by myspulin** [comment]
Hi @crazy-max ,

I have two laptops, on the first of them I have reported the problem in the first part of this ticket. On the second one I did migration from 1.0.21 to 1.0.22 following the UPGRADE.md. Then I have installed PHP 7.1.0, upgrade to Apache v2.4.9 and get the same error:

PHP Warning:  PHP Startup: Unable to load dynamic library 'C:/Data/neard/bin/php/php7.1.0/ext\\php_curl.dll' - %1 nelze spustit.\r\n in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:/Data/neard/bin/php/php7.1.0/ext\\php_openssl.dll' - %1 nelze spustit.\r\n in Unknown on line 0

But when I upgrade to the latest Apache v2.4.23 it works normally and both extensions is loaded correctly.

So it looks like the Apache problem, the older version is maybe compiled in a different way, so dll library cannot be loaded.

After migration to the latest versions it works on both laptops. Just close this issue, thank you!

**Comment by diovoemor** [comment]
> So it looks like the Apache problem, the older version is maybe compiled in a different way, so dll library cannot be loaded.
No, it's an OpenSSL version mismatch problem possibly compounded by Visual C++ version mismatch problem as well.
Apache 2.4.9 came with OpenSSL 1.0.1 and PHP7 uses 1.0.2 and when running php as a module (phpXapache2_4.dll  X=5or7) PHP uses the OpenSSL from Apache which is shared. So if Apache's OpenSSL is 1.0.1 and you try running PHP7, it ain't gonna work because the OpenSSL DLLs have different internal structures.

Similar with VC versions as well. Common belief is that Apache VC14 can run modules of all prior VC versions but not the other way around. So with that VC9/10/11 builds of Apache cannot run PHP7 as a module. I've never cared to test the value of this belief but simply keep it in mind when it comes to loading 3rd party modules in Apache.

**Comment by crazy-max** [comment]
Ok, what is the release number of your apache bundle ?
Neard 1.0.22 requires the r4 bundle for Apache.

**Comment by crazy-max** [comment]
Ok so it's linked to the OpenSSL version like you said.
I will make some tests with the Apache 2.4.9 version.

**Comment by crazy-max** [comment]
Infos have been added on the module page of [Apache](http://neard.io/bins/apache/#openssl) and [PHP](http://neard.io/bins/php/#openssl).
As Apache is on top of PHP (php is loaded as a module for now), Apache OpenSSL version must be equal or greater than OpenSSL version of PHP. I will add a FAQ section about this question.
If you have other suggestions, do not hesitate.
