### ISSUE TITLE
Phpmyadmin doesn't show my database

### ISSUE THREAD

**Issue by berthos** [crazy-max/neard#201]
Here is my setup : 
Windows 10 Famille 64 Bits
Neard 1.0.22

I have just updated my neard from the previous version and after having done the required items from the upgrade.md, I have opened the phpmyadmin and there was only the informations_schema database but not my different databases.
I have looked in the folder neard\bin\mysql\mysql5.5.24\data : all the files of my databases are here.

How can I relink my databases in Phpmyadmin ?

Here are the logs : [http://aleph2at.free.fr/autres/neard/core_tmp.zip](http://aleph2at.free.fr/autres/neard/core_tmp.zip)

Thanks

**Comment by crazy-max** [comment]
Hi,

I also need the `neard\logs` folder.
Can you upload it?

Thanks

**Comment by berthos** [comment]
Here are the logs : [http://aleph2at.free.fr/autres/neard/neard_logs.zip](http://aleph2at.free.fr/autres/neard/neard_logs.zip)

**Comment by crazy-max** [comment]
Thanks

Have you updated your Apache version (2.2.22) with the latest [Apache bundle](https://github.com/crazy-max/neard-bin-apache/releases) required for Neard 1.0.22 ?

Can you send me this file : `neard\alias\phpmyadmin.conf` ?

Have you tried with Adminer app ?

**Comment by berthos** [comment]
I have the apache 2.2.22 version.
Here is the file : [http://aleph2at.free.fr/autres/neard/phpmyadmin.zip](http://aleph2at.free.fr/autres/neard/phpmyadmin.zip)

**Comment by crazy-max** [comment]
But have you installed the latest bundle ? (r4 : neard-apache-2.2.22-r4.7z)
And can you check if you see your dbs with Adminer ? (http://localhost/adminer)

Thanks

**Comment by berthos** [comment]
I have the last bundle and with the adminer I see the same database than with the phpmyadmin but not mine

**Comment by crazy-max** [comment]
Ok so there is something wrong with your database not phpmyadmin.

Can you open a console from Neard (Left click in the systray > Tools > Console), then open a new MySQL tab, type the command `SHOW GRANTS;` and post the result :

![image](https://cloud.githubusercontent.com/assets/1951866/21495440/ae3085ca-cc17-11e6-8a80-1b540fdbb81a.png)

**Comment by berthos** [comment]
Here is the result : [http://aleph2at.free.fr/autres/neard/clipboard01.jpg](http://aleph2at.free.fr/autres/neard/clipboard01.jpg)

**Comment by crazy-max** [comment]
The screenshot is not available on this link (you can drag & drop pictures on the post directly)

**Comment by berthos** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/15923548/21495670/3eb54c92-cc19-11e6-88a5-46410ab5827e.jpg)

**Comment by berthos** [comment]
Each time I do an update of neard, I have to execute this command 
CREATE USER 'aleph2at'@'%' IDENTIFIED BY '***';GRANT ALL PRIVILEGES ON *.* TO 'aleph2at'@'%' IDENTIFIED BY '***' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0MAX_USER_CONNECTIONS 0;

But this time the command was refused with the error message : 
#1227 - Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation

**Comment by crazy-max** [comment]
Very strange i don't have to do that when i upgrade Neard.
Can you send me these files :
* `neard\bin\mysql\mysql5.5.24\my.ini`
* `neard\bin\mysql\mysql5.5.24\neard.conf`

**Comment by berthos** [comment]
Here are the files : [http://aleph2at.free.fr/autres/neard/mysql5.5.24.zip](http://aleph2at.free.fr/autres/neard/mysql5.5.24.zip)

**Comment by berthos** [comment]
Do you want to connect with teamviewer ? Perhaps it could be easier for you

**Comment by berthos** [comment]
Hi

I don't remember what I have changed, but now I can see my databases in Adminer.
But still not in phpmyadmin

**Comment by crazy-max** [comment]
Hi,

Have you tried to clear the cache of your browser (cookies) ?

**Comment by berthos** [comment]
Hi,

I have the same problem by using another webbrowser (IE) so it is not a problem of cache.

I am using admin user because I can't create a new user

In PhpMyadmin I can't create a new database but I can do it in adminer and I can see the test database in phpmyadmin

**Comment by berthos** [comment]
Thanks to the console, I have recreated my user. And then in Adminer and in Phpmyadmin, I can see my databases... but .... in my main database, both of the applications show me all the tables but only 2 of them are accessible. For the other one, when I click, the app says : the table doesn't exist. :(

**Comment by crazy-max** [comment]
@berthos Do you solved this issue ?
For me it's linked to your configuration on your database.
Have you tried to reinstall phpMyAdmin with the latest bundle available ?
Or reinstall MySQL and import your databases ?

**Comment by berthos** [comment]
My statut is : after reinstalling PhpMyAdmin bundle
- The problem of the tables remain the same
- And the user problem remain the same.

So I decided  to reimport my database from a backup (not up to date sadly) 
Now I can access to my database but not with the user used for 13 years.

On free.fr, I have :
```
GRANT USAGE ON *.* TO 'aleph2at'@'172.20.%' IDENTIFIED BY PASSWORD '***********'
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE ON `aleph2at`.* TO 'aleph2at'@'172.20.%'
```

On localhost, I have :
```
GRANT USAGE ON *.* TO 'aleph2at'@'localhost' IDENTIFIED BY PASSWORD '************'
GRANT ALL PRIVILEGES ON `aleph2at_test`.* TO 'aleph2at'@'localhost' WITH GRANT OPTION
```

and also 
```
GRANT USAGE ON *.* TO 'aleph2at'@'127.0.0.1' IDENTIFIED BY PASSWORD '************'
GRANT ALL PRIVILEGES ON `aleph2at_test`.* TO 'aleph2at'@'127.0.0.1' WITH GRANT OPTION
```

With the root account I can connect on my database.
For the localhost root account I have  :

```
GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION
GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION
```

**Comment by crazy-max** [comment]
Ok so the issue it's just for your custom username ?

If this the case i suggest you split the configuration for your project to use the mysql username root on development (on neard) and your mysql username aleph2at on production.

Quick example :

```php
if ($_SERVER['HTTP_HOST'] == 'localhost')
{
  // development
  $mysql = new PDO('mysql:host=127.0.0.1;port=3306;dbname=aleph2at', 'root', '');
  ...
}
else
{
  // production
  $mysql = new PDO('mysql:host=127.0.0.1;port=3306;dbname=aleph2at', 'aleph2at', '******');
  ...
}
```

Or you can post your issue on [stackoverflow](https://stackoverflow.com/) or [superuser.com](https://superuser.com).
