### ISSUE TITLE
Localhost menu shortcuts don't reflect Apache port change

### ISSUE THREAD

**Issue by JJohnson1988** [crazy-max/neard#205]
If Apache port is changed to a value other than 80, the Localhost and Localhost (SSL) shortcuts at the top of the menu should take you to a localhost address in your browser with the non-standard port appended.

For example, if I changed the Apache port to 8080, the Localhost shortcut at the very top should take me to the "localhost:8080" address within the specified browser.

**Comment by crazy-max** [comment]
Will be fixed on the next release
