### ISSUE TITLE
MySQL console dont ask db password

### ISSUE THREAD

**Issue by Jmos** [crazy-max/neard#206]
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

[User@MACHINE x:\neard\bin\mysql\mysql5.5.24]

**Comment by crazy-max** [comment]
Hi,

Please read the [Reporting an issue page](http://neard.io/doc/reporting-issue)

**Comment by Jmos** [comment]
win 7 64 
neard 1.0.22
MySQL **has** password

[cor_tmp.zip](https://github.com/crazy-max/neard/files/721864/cor_tmp.zip)
[logs.zip](https://github.com/crazy-max/neard/files/721863/logs.zip)
![2017-01-22_111638](https://cloud.githubusercontent.com/assets/5389792/22181858/b1331a8e-e095-11e6-93ec-adcf53b5e269.png)

I hope all information is enough and I did not forget anything

**Comment by crazy-max** [comment]
Password will be asked for root user if not empty on the next release :

![image](https://cloud.githubusercontent.com/assets/1951866/22224559/5d425586-e1bf-11e6-83da-f0374c2afa3c.png)
