### ISSUE TITLE
can't change limit import of sql file in phpmyadmin

### ISSUE THREAD

**Issue by gauthierb** [crazy-max/neard#214]
Hi,

i have change the upload_max_filesize, memory_limit and post_max_size in the php.ini and nothing change after restart apache, quit neard and start again, the limit stay at Max: 128MiB, how can i change this?
I'm on windows 10 x64, and neard 1.0.22

thanks for help

**Comment by gauthierb** [comment]
ok sorry i have found how to do this need to change phpmyadmin.conf in neard/alias, think was the same value has php.ini

**Comment by crazy-max** [comment]
You right these values have to be changed in the alias conf
