### ISSUE TITLE
Neard .Exe Detected as Delphi Programming Language!

### ISSUE THREAD

**Issue by blaisexen** [crazy-max/neard#215]
Is this Ok, since I know a lot of Delphi Programs are known to be viruses?

Should I keep the File?
I'm not down grading Delphi programs but I just want to be sure it's safe.

anyway, I will try and as I know Delphi programs are one of the best programming language, so I think I will trust the installation.

thank you

**Comment by crazy-max** [comment]
Hi,

Yes indeed `neard.exe` is a Delphi Program based on Aestan Tray Menu 1.6.2.
It's virus free as you can see on the [VirusTotal scan].(https://www.virustotal.com/en/file/bed8eeffb63e893b1053fb4ca3a73e24a4e659face21589045165d3238770e11/analysis/))
You can have more info in the [FAQ](http://neard.io/doc/faq/#where-is-the-source-code-of-neardexe-).

Thanks

**Comment by blaisexen** [comment]
Good to hear that it's Ok,

thank you

**Comment by pratham2003** [comment]
Avast caught this as a virus too and 'disinfected' it.
Is there anyway to get in touch with these 'Anti-virus' devs and this white-listed?

**Comment by crazy-max** [comment]
Hi @pratham2003, It's virus free as you can see on this [VirusTotal scan](https://www.virustotal.com/#/file/bed8eeffb63e893b1053fb4ca3a73e24a4e659face21589045165d3238770e11/detection) as well with your AV.

What you can do is [send a report to BitDefender](https://www.bitdefender.com/submit/). Can you do that and give me their answer ?

Thanks

**Comment by blaisexen** [comment]
It's a false positive alarm, so it's safe.
