### ISSUE TITLE
Ghostscript

### ISSUE THREAD

**Issue by StaggerLeee** [crazy-max/neard#220]
How to install Ghostscript together with ImageMagick on Neard ? 
Is it possible to add it to Neard as Tools module ?
ImageMagick is installed and detected well of course.

https://www.ghostscript.com/

I need it for new PDF thumbnails manipulation, now in core of WordPress 4.7 and above versions.

Thanks for any answer.

**Comment by crazy-max** [comment]
Hi,

I will take a look on your suggestion!
Thanks!

**Comment by StaggerLeee** [comment]
Thank you. It is for your benefit also, considering how many WordPress installations are out there. (developing needed for each new one)

You decide if issue will be closed.

**Comment by crazy-max** [comment]
Ghostscript is available in the [latest 1.2.16 unstable release](https://github.com/crazy-max/neard/releases/tag/v1.2.16)

**Comment by StaggerLeee** [comment]
Thank you for Ghostscript support.
Problem is I still cannot it make to work. Do you have time for some short manual ? Or any better to install WordPress and try to generate PDF thumbnails from them.

I uninstalled my Imagemagick and Ghostscript I installed in Windows 10. Before it with some mixing of different tutorials made it to work. 

Now not anymore. Do some lines need to be added in PHP, Apache conf files ?

![Image of Yaktocat](https://s26.postimg.org/vjea3712x/2017-09-02_190601.jpg)

**Comment by StaggerLeee** [comment]
Anyway, cannot lose more time on it as it is just localhost testing. Hosting servers probably have all configured, so no need to worry about it.

I managed somehow via this tutorial: 
https://kau-boys.de/3194/adventskalender/pdf-vorschaubilder-von-wordpress-4-7-in-xampp-unter-windows-verwenden

Just installed both ImageMagick and Ghostscript Windows exe inside Neard folder, to have all in one place. And adjusted windows enviroment paths accordinly.

This WordPress plugin complains same thing, but Ghostscript is now making PDF thumbnails.
Seems strange, but this part in tutorial about copying all .dll files from ImageMagick-x.x.x-x-vc14-x86.zip, to D:\Neard\bin\apache\apache2.4.27 is crucial. Without this I cannot make Ghostscript to work, no matter what.

Anyway, just a bit info for other Neard Users who want it activated on localhost.
Drag this link via Google translate and follow steps.

**Comment by crazy-max** [comment]
Hi @StaggerLeee,

Thanks for your feedback about Ghostscript and Imagick!
Can you please open a new issue for your problem ?

Thnks for your contrib!

**Comment by StaggerLeee** [comment]
Hi @crazy-max,

I cannot open new issue as I am not sure if I understand roles of ImageMagick and Ghostscript in Neard. I do not know is it, as it is now, by fashion, or what.

Are those 2 tools in Neard supposed to work with Apache, PHP on default ? Without any tweaking. Now I am not sure it is possible.
Or they are just 2 additional tools as side help, separate from servers.

**Comment by crazy-max** [comment]
@StaggerLeee Yes they are supposed to work with Apache and PHP as they are included in the env var PATH to work with.

If you go to http://localhost/?p=phpinfo, you can check that imagick extension is loaded :

![image](https://user-images.githubusercontent.com/1951866/30002736-4962a4b6-90b1-11e7-9035-369aeac06092.png)

I have installed the latest release of Wordpress to check your issue but can you tell me where i can find the page "PDF Thumbnails Support test" on Wordpress ?

**Comment by crazy-max** [comment]
Ok i have found the **PDF Thumbnails Support Test** plugin!

![image](https://user-images.githubusercontent.com/1951866/30002781-0cbdb658-90b2-11e7-9b86-e0680ec99b4a.png)

**Comment by StaggerLeee** [comment]
Dont trust blindly this plugin. It has problem detecting Ghostscript in some cases.
https://github.com/ethanclevenger91/pdf-thumbnails-support-test/issues/1

Go to the Media Manager and simply upload a PDF. For 2 second you will see if Ghostscript is working on server. If there is no PDF thumbnail, it does not work.

**Comment by crazy-max** [comment]
Ok the problem is that **PDF Thumbnails Support Test** plugin is Linux specific.
After investigate on the source code of the plugin, it checks :

* ImageMagick: `convert -v` : KO on my computer because convert is loaded from `C:\Windows\System32\convert.exe` instead of `neard\tools\imagemagick\`
* Imagick: `extension_loaded('imagick')` : OK here
* Ghostscript: `which gs` instead of `where gswin32c.exe` for Windows.

**Comment by crazy-max** [comment]
Ok, after changing some things on Neard, ImageMagick is OK :

![image](https://user-images.githubusercontent.com/1951866/30002892-8f1fde12-90b4-11e7-8af3-5b9660eb21cf.png)

In the file `neard\core\classes\class.win32service.php` replace lines 148-157 with :

```
if ($this->getNssm() instanceof Nssm) {
    $nssmEnvPath = Util::getAppBinsRegKey(false);
    $nssmEnvPath .= Util::getNssmEnvPaths();
    $nssmEnvPath .= '%SystemRoot%/system32;';
    $nssmEnvPath .= '%SystemRoot%;';
    $nssmEnvPath .= '%SystemRoot%/system32/Wbem;';
    $nssmEnvPath .= '%SystemRoot%/system32/WindowsPowerShell/v1.0';
    $this->getNssm()->setEnvironmentExtra('PATH=' . $nssmEnvPath);
    return $this->getNssm()->create();
}
```

**Comment by StaggerLeee** [comment]
Thing is I cannot make it to work in Neard unless I put all .dll files in active Apache bin folder. 
**D:\Neard\bin\apache\apache2.4.27\bin**

Or I make something wrong totally.

As I see all those .dll files are not inside ImageMagick & Ghostscript folders inside tools folder. Need to download them and put inside apache bin folder.

**Comment by crazy-max** [comment]
@StaggerLeee Can you post a screenshot of imagick section in your phpinfo (http://localhost/?p=phpinfo) ?

![image](https://user-images.githubusercontent.com/1951866/30002955-ae23da78-90b6-11e7-9c67-5e5b550a67a4.png)

I think i have found an issue with `ImageMagick supported formats = no value`.

**Comment by StaggerLeee** [comment]
I have "formats",  as Ghostscript is installed "outside" Neard and recognized right.
Maybe you dont know. ImageMagick cannot alone generate thumbnails from PDF files. Ghostscript is needed for that.

![Image of Yaktocat](https://s26.postimg.org/a5py9hd89/2017-09-03_145107.jpg)

**Comment by crazy-max** [comment]
Yep i know Ghostscript is required but i have to figure out why i don't have all these ImageMagick supported formats like you ;)

What files have you added in `apache/bin` please ?

**Comment by StaggerLeee** [comment]
I wrote above. I installed ImageMagick too as there is none in Neard. Maybe that windows installation and enviroment paths added fromats. Do not know now for sure, it is really complicated. To many steps to get it to work.

dll files inside active Apache bin folder are all .dll files from this ZIP: 
http://windows.php.net/downloads/pecl/deps/ImageMagick-6.9.3-7-vc14-x86.zip

(VC14 - x86)

**Comment by crazy-max** [comment]
Ok i see, there are missing dlls with the current imagick extension (3.4.3). Only these DLLs are included in `neard\bin\php\php7.1.8\imagick` :

![image](https://user-images.githubusercontent.com/1951866/30003115-30df360e-90b9-11e7-9b11-b5d4bfb084fb.png)

I have to include the deps from PECL like you said.

**Comment by crazy-max** [comment]
Confirmed, i have forgot PECL deps :

![image](https://user-images.githubusercontent.com/1951866/30003184-e27fb528-90b9-11e7-8daf-e8fb8c8bac9d.png)

**Comment by crazy-max** [comment]
Now formats are loaded :

![image](https://user-images.githubusercontent.com/1951866/30003228-74080f36-90ba-11e7-8566-3d8bee18d634.png)

By copying everything from `ImageMagick-6.9.3-7-vc14-x86.zip` to `neard\bin\php\php7.1.8\imagick`.

**Comment by StaggerLeee** [comment]
Let me uninstall ImageMagick & Ghostscript from Windows, remove their Enviroment Variables and test with only this PECL dependency solution. Will be back shortly.

**Comment by crazy-max** [comment]
@StaggerLeee Thanks for your support

**Comment by crazy-max** [comment]
Ok now with Ghoscript when i try to use ImageMagick to convert PDF i've got this error :

```
C:\Users\crazy>C:\neard\bin\php\php7.1.8\imagick\convert.exe "C:\Users\crazy\Desktop\pdf-sample.pdf" test.png
convert.exe: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/706.
convert.exe: FailedToExecuteCommand `"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72"  "-sOutputFile=C:/Users/crazy/AppData/Local/Temp/magick-96248uLsgd34j_Tf%d" "-fC:/Users/crazy/AppData/Local/Temp/magick-96245oyv3XDug7_O" "-fC:/Users/crazy/AppData/Local/Temp/magick-9624ut9X5XIe8DyZ"' (Le fichier spécifié est introuvable.) @ error/delegate.c/ExternalDelegateCommand/480.
convert.exe: PDFDelegateFailed `Le fichier spécifié est introuvable.' @ error/pdf.c/ReadPDFImage/801.
convert.exe: NoImagesDefined `test.png' @ error/convert.c/ConvertImageCommand/3252.
```

But if i rename `gswin32c.exe` to `gs.exe` in `neard\tools\ghostscript\ghostscript9.21\bin` , now it works like a charm :

![image](https://user-images.githubusercontent.com/1951866/30003333-c9ae378e-90bb-11e7-9dae-37f1ac454d3f.png)

**Comment by StaggerLeee** [comment]
Yes it is working now, thank you.
For other Neard Users:

- Download dependency package from this link, x86, V14, latest ImageMagick:
http://windows.php.net/downloads/pecl/deps/
- Everything inside "bin" folder in this ZIP copy into your PHP active folder/imagemagick subfolder (I did overwrite Neard files already in)

- It is all, no tweaking with Windows and enviroment variables needed.

**Comment by crazy-max** [comment]
To summary your issue, i have to :

* Include PECL deps of ImageMagick in `php\imagick`
* Copy `gswin32c.exe` to `gs.exe`

**Comment by StaggerLeee** [comment]
Put both those .exe (copies) in future releases, just to be sure. Not so big deal, they are small files:
gswin32c.exe and gs.exe
I wonder why I did not get same Ghostscript error. Just tested with PDF upload in WordPress. You do it from CMD console ?

**Comment by crazy-max** [comment]
Yep from CMD because `gswin32c.exe` does not redirect errors to stdout

**Comment by StaggerLeee** [comment]
@crazy-max,

This is very important point for all Neard users using this. Even for me to understand it right, and not to do things by heart.

Did you just extract whole ZIP content inside imagemagick PHP subfolder ?
When I did it it did not work. Had to extract content from ZIPs bin subfolder.

**Comment by crazy-max** [comment]
Yes the bin folder of course! (you can remove *.pdb files) :

![image](https://user-images.githubusercontent.com/1951866/30003527-bf9881b6-90be-11e7-94d4-313c51732028.png)

In `php\php7.1.8\imagick` :

![image](https://user-images.githubusercontent.com/1951866/30003530-d8138de4-90be-11e7-8f76-a538407a0011.png)

**Comment by crazy-max** [comment]
I will create a new issue to explain everything

**Comment by N6REJ** [comment]
I have loved following this discussion.  Is the thumbnail generated automatically or is something else needed in html to make this happen?

**Comment by StaggerLeee** [comment]
In WordPress it is handled automatically when Ghostscript is detected. Plugin and third party code do not have to do anything special with code.
