### ISSUE TITLE
Can't start Python 3.6.0.0

### ISSUE THREAD

**Issue by the-veloper** [crazy-max/neard#221]
Installed Neard 1.0.22 on Windows 10 x64. Then downloaded Python 3.6.0.0 and configured pythonVersion = "3.6.0.0" .

Trying to start Python gives the following error:

> TCC: Unknown command "" "E:\Portable\Neard\tools\python\python3.6.0.0python3.6.0\python-3.6.0b3\python.exe"

Here are the tmp.zip and logs.zip:
https://www.sendspace.com/filegroup/ourxCkt4M5Jtor0U1kZ6cQ

Screenshot:
http://imgur.com/7hsU8qo

**Comment by crazy-max** [comment]
Hi @the-veloper,

Seems to be a problem with the version string in the main `neard.conf` file.
Can you post these files here plz :

* `E:\Portable\Neard\neard.conf`
* `E:\Portable\Neard\tools\python\python3.6.0.0\neard.conf`

Thanks for your feedback!

**Comment by the-veloper** [comment]
Thank you for the fast reply @crazy-max, great work on the project!

Here are the files as requested:
http://pastebin.com/XnCPhXgv
http://pastebin.com/yhS0SwuP

**Comment by crazy-max** [comment]
Ok can you go to the issue #222 and replace this file `E:\Portable\Neard\tools\python\python3.6.0.0\neard.conf` with the fixed content ?

Then tell me if it works.
Thanks for your support.

**Comment by the-veloper** [comment]
Now I have this error:
http://imgur.com/3xt4LvJ

**Comment by crazy-max** [comment]
Hum where the folder `python3.6.0.0python3.6.0` comes from ?
What is inside this folder ?

**Comment by the-veloper** [comment]
Every time I try to run Python from Neard, this folder is created.
I have tried to delete it but it spawns again.

Here is the structure:
> E:\Portable\Neard\tools\python\python3.6.0.0python3.6.0>tree /f
> E:.
> └───settings
>     │   winpython.ini
>     │
>     └───.spyder-py3
>             workingdir

**Comment by crazy-max** [comment]
Ok i'm able to reproduce your issue.
I will find a fix asap.

Thanks for your support!

**Comment by the-veloper** [comment]
Thank you for your time.
I will wait for updates.

BTW: The fix from #222 fixed my index.php that comes with this version of Neard. Before the fix I could not see all the features, because the index crashed when it got to the Python part.

**Comment by crazy-max** [comment]
Seems to be a bug on the `env.bat` of WinPython.

Open the file `E:\Portable\Neard\tools\python\python3.6.0.0\scripts\env.bat` and replace this :

```
@echo off
set WINPYDIRBASE=%~dp0..
rem get a normalize path
CALL :NORMALIZEPATH "%WINPYDIRBASE%"
set WINPYDIRBASE=%RETVAL%
set RETVAL=
```

By

```
@echo off
set WINPYDIRBASETMP=%~dp0..
pushd %WINPYDIRBASETMP%
set WINPYDIRBASE=%CD%
popd
```

And tell me if it works for you

**Comment by the-veloper** [comment]
It works!

Thank you @crazy-max. 

BTW: I am impatient to see how this project grows even bigger with other useful tools. I would propose integrating http://strawberryperl.com/releases.html .

Have a great day.

**Comment by crazy-max** [comment]
Ok great and yes Perl is already in the pipeline (issue #155) ;)

**Comment by crazy-max** [comment]
Available here : http://neard.io/tools/python/#releases
