### ISSUE TITLE
New control panel

### ISSUE THREAD

**Issue by StaggerLeee** [crazy-max/neard#228]
Did you have thoughts about switching to some new control panel platform ?

As I could see it Aestan tray is very limited in sense how we could change and adapt it. Found it most problematic to build own sprite icons.
And very old, not much Info and tutorials around Net. I found zero help searching for it. Some is there but Wamp5 specific.

Sorry, clicked wrong, edit comes in few second.

**Comment by StaggerLeee** [comment]
Some benefits:

- Icon can be bigger. Aestan makes problems for Users working with notebook pad instead of mouse. Even for less sensitive mouses. Icons are unnecessary small, remains from old Internet.

- Icons can be used from SVG icon pack.. There are some for precise this thing and with GPL licences.

- We could rearrange, adapt control panel (PHP, HTML, CSS) and share it here with other Users.

- Localhost template as it is now is very good start (Bootstrap). Some controls specific for PHP, Apache, MySql launching/changing can be done in Bootstrap modal (or not, depends). All is already inside.

- It could look like there is not much space on Localhost page now but it is not so. There is much empty space and some blocks unnecessary huge to fill space.

- To not confuse first time Neard users clicking on neard.exe could automatically open default browser and localhost start page.

- Rest depends of course on free time and will. Is it possible to have chosing of PHP/Apache modules via browser and PHP code. How difficult it is. Is it worth bothering, etc...

**EasyPHP** moved everything to Localhost Start page. (Except control exe launch, needed allways)

![](https://blog.amasty.com/wp-content/uploads/2016/02/Start-your-EasyPHP-DevServer-2.png)

![](http://www.easyphp.org/images_easyphp/screenshots/EasyPHP-Webserver-14.1-beta-screenshot_01.png)

![](https://pbs.twimg.com/media/Cqd06DHUkAEhwCL.jpg)

**Comment by crazy-max** [comment]
Yes indeed, as you can see there is a milestone named neard-2.0.0
I'm working on it since several weeks. Electron is used on this next milestone.

**Comment by crazy-max** [comment]
Btw thanks for your input!

**Comment by StaggerLeee** [comment]
Thank you.

Seems very interresting, if it is right Electron I am looking at.
Will just close this.

**Comment by crazy-max** [comment]
Yep indeed this Electron : https://electron.atom.io/ with an embedded chromium ;)
