### ISSUE TITLE
Improve phpinfo output

### ISSUE THREAD

**Issue by StaggerLeee** [crazy-max/neard#230]
Script doesnt make space after comma "," and Chrome has some strange problem how to use word-wrap, layout goes out of screen, with horizontal scroll.

For instance this is detected as just one word:

> C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0;D:\Neard\bin\apache\apache2.4.23\bin;D:\Neard\bin\php\php7.1.2;D:\Neard\bin\php\php7.1.2\pear;D:\Neard\bin\php\php7.1.2\imagick;D:\Neard\tools\composer\composer1.1.2;D:\Neard\tools\drush\drush7.3.0;D:\Neard\tools\git\git2.9.0\bin;D:\Neard\tools\imagemagick\imagemagick6.9.3-10;D:\Neard\tools\phpmetrics\phpmetrics1.0.1;D:\Neard\tools\phpunit\phpunit4.8.26;D:\Neard\tools\python\python2.7.12.3\bin;D:\Neard\tools\ruby\ruby2.0.0.p648\bin;D:\Neard\tools\wpcli\wpcli0.20.4;

I changed a bit CSS inside "D:\Neard\core\resources\homepage\tpls" hp.phpinfo.php.
- Fixed this problem in Chrome
- Added some paddings
- Changed colors to less attacking
- Increased font-size

Reason for doing so is out of 100 usage of phpinfo.php maybe less than 5% is done by mouse scrolling. So paddings and font-size actually no matter, as most people first thing they do inside this screen is to use F3 search in browser, to find what they are looking for. 

If someone want to test it is here:

```
<style type="text/css">
  #phpinfo {}
  #phpinfo pre {margin: 0px; font-family: monospace;}
  #phpinfo a:link {color: #000099; text-decoration: none; background-color: #ffffff;}
  #phpinfo a:hover {text-decoration: underline;}
  #phpinfo table {border-collapse: collapse;}
  #phpinfo .center {text-align: center;}
  #phpinfo .center table {margin-left: auto; margin-right: auto; text-align: left; margin-bottom: 10px; }
  #phpinfo .center th {text-align: center !important;}
  #phpinfo td, th {border: 1px solid #ddd; font-size: 85%; vertical-align: baseline; padding: 10px; }
  #phpinfo td.v {word-wrap: break-word; word-break: break-all; }
  #phpinfo h1 {font-size: 150%;}
  #phpinfo h2 {font-size: 125%;}
  #phpinfo .p {text-align: left;}
  #phpinfo .e {background-color: #fcf8e3; font-weight: bold; color: #000000;}
  #phpinfo .h {background-color: #d9edf7; font-weight: bold; color: #000000;}
  #phpinfo .v {background-color: #f5f5f5; color: #000000;}
  #phpinfo .vr {background-color: #cccccc; text-align: right; color: #000000;}
  #phpinfo img {float: right; border: 0px;}
  #phpinfo hr {}
</style>
```

**Comment by crazy-max** [comment]
Thanks for your contrib, i will check and implement your enhancement

**Comment by crazy-max** [comment]
I have made some changes, can you try the latest [hp.phpinfo.php](/crazy-max/neard/blob/master/core/resources/homepage/tpls/hp.phpinfo.php) ?

**Comment by StaggerLeee** [comment]
Thank you. I will keep your, much better than mine. 
Tried all Wamp possible platforms, this one is best as I can recall.
