### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by teamayu** [crazy-max/neard#238]
The application won`t start for me. I`m running Windows 10 64Bit.

I set the logsVerbose to 2, but there is nothing in the logs or core/tmp folders.

I downloaded neard and added the following to the relevant bin folders:

php5.6.30, apache2.4.23 & mysql5.6.34

I checked that WSH and SETX is available and they are. I also installed the prerequisites.

When I run neard.exe I get the error shown in the screenshot.

![23-03-2017-111725](https://cloud.githubusercontent.com/assets/10624092/24230495/6a68b9fc-0fba-11e7-942a-19a6ef3a4c92.png)

**Comment by teamayu** [comment]
Sorry, figured it out. I had downloaded the master zip from Github, which has a different structure.

**Comment by crazy-max** [comment]
Yes download links are available on the official website : http://neard.io/release/latest
