### ISSUE TITLE
#1231 - Variable 'lc_messages' can't be set to the value of 'fr_FR'

### ISSUE THREAD

**Issue by eric13500** [crazy-max/neard#241]
Hi !

It's impossible for me to turn PhpMyAdmin to French...

Thanks for your help

**Comment by crazy-max** [comment]
Hi,

Try this solution : https://support.plesk.com/hc/en-us/articles/213952625-phpMyAdmin-login-issue

**Comment by eric13500** [comment]
Hi !

Thanks for your answer.

I saw this solution, but don't find the my.cnf file to do this...

Can you help me ?

Regards

**Comment by crazy-max** [comment]
Yes it is

**Comment by eric13500** [comment]
Done, but don't work better...

**Comment by crazy-max** [comment]
Ok i will investigate on your issue

**Comment by dcanl** [comment]
Same problem here since few versions of phpmyadmin in neard...

Solved by renaming the [version of phpmyadmin]\locale\fr folder to fr_FR ... No more label "Français - French" in language list (only fr_FR) but it work!

**Comment by eric13500** [comment]
Thanks @dcanl !

Works fine !

But it's an issue that must be fixed !

This workaround should help you find the fix...

Thanks to the team for your future update fixing it !

**Comment by crazy-max** [comment]
Thanks @dcanl

What is your MySQL and PhpMyAdmin version?

**Comment by dcanl** [comment]
phpMyAdmin 4.6.4 (p4)
MySQL 5.6.27

**Comment by eric13500** [comment]
PhpMyAdmin 4.6.6 (4p5)
MySql 5.5.24

**Comment by crazy-max** [comment]
Ok guys thansk for your input.

Can you try to clear cookies for http://localhost/phpmyadmin (More info [here](https://stackoverflow.com/questions/41977950/phpmyadmin-error-1649-unknown-locale))

For `pma_lang` cookie i have on my local computer `fr` has value :

![image](https://cloud.githubusercontent.com/assets/1951866/24875355/0c8ff6ca-1e28-11e7-8356-b4decc4d76c7.png)

I've found a similar issue phpmyadmin/phpmyadmin#11789 on the official phpmyadmin repository and they have implemented a mapping between mysql and phpmyadmin locales since 4.6.0.

**Comment by dcanl** [comment]
I cleared cookies and ... always the same problem.

After checking, pma_lang contains fr as well.

![image](https://cloud.githubusercontent.com/assets/7107676/24879210/65386b50-1e36-11e7-936f-2b7283444fbd.png)

If you choose french language on the phpmyadmin connection screen, connection form is translated but problem occurs when submitting connection form.

If you let english language, connection is ok and problem occurs when you choose French on the phpmyadmin home screen.

Strange thing: the problem occurs only on local MySQL connection. I have a remote MySQL instance which I manage through neard phpmyadmin, and it works well (MySQL 5.5.44 on a debian server).

If the french folder is renamed from fr to fr_FR, it works for both (neard pma/localhost mysql, and neard pma/remote mysql). 

Note that if folder is renamed (and cookies emptied), there's no more automatic locale recognition (english by default). With folder "fr", French language is automaticly selected on login screen.

Updated to phpmyadmin 4.6.6 (4p5 with local MySQL 5.6.27), problem still occurs. 

No problem with phpmyadmin 4.4.15.8 (phpmyadmin4p4) neither with 4.4.15.10 (phpmyadmin4p5).

I hope I helped.

**Comment by crazy-max** [comment]
Thank you for this detailed report!
I keep you in touch!

**Comment by crazy-max** [comment]
I was able to reproduce your issue and i have track to solve it temporarly :

Edit your `config.inc.php` and add this line :

```php
$cfg['Lang'] = 'en_GB';
```

With this modification, the english language will be forced.

The original problem comes from the mysql module. The module has only the english language. That's why you've got this error.
I will made new bundles of MySQL soon to solve this issue.

**Comment by crazy-max** [comment]
Same issue for MariaDB

**Comment by dcanl** [comment]
Hum... Yes it works, it forces english language in phpmyadmin, but the aim was to use french language.

Forcing en_GB in config file make the language menu disappear from phpmyadmin, so it's locked to english.

For now, I personnaly prefer my current (and temporary) solution renaming fr folder to fr_FR to get phpmyadmin working in french! ;-)

But I understood what you said, and I will wait for your next bundle of MySQL with french!

Thanks!

**Comment by crazy-max** [comment]
Solved for MariaDB, more info : http://neard.io/news/2017-04-13-mariadb-10.0.30-10.1.22-available/

**Comment by crazy-max** [comment]
Now solved for MySQL : http://neard.io/news/2017-04-13-mysql-5.5.55-5.6.36-5.7.18-available/

**Comment by dcanl** [comment]
Thank you very much, now working like a charm ! 👍

**Comment by slutbert** [comment]
IN '/usr/share/phpmyadmin/libraries/classes/DatabaseInterface.php'

COMMENT THE FOLLOWING CODE LIKE SHOWN :

        /* Locale for messages */
        $locale = LanguageManager::getInstance()->getCurrentLanguage()->getMySQLLocale();
        **/*
        if (! empty($locale)) {
            $this->query(
                "SET lc_messages = '" . $locale . "';",
                DatabaseInterface::CONNECT_USER,
                self::QUERY_STORE
            );
        }
        */**

**Comment by nemihome** [comment]
This bug is still existing with 5.2.1 in combination with mariadb 10.6.12 and at least with SSL connection - not sure if that is relevant but the above coding snippend or setting language to en helped.
