### ISSUE TITLE
Services cannot start / paused on Win 10 Creators Update

### ISSUE THREAD

**Issue by dcanl** [crazy-max/neard#242]
Hi,

Since the Windows update to "Creators Update", services neardapache, neardmailhog and neadmemcached doesn't start properly, they go in "paused" status immediately.

As suggested [here](https://nssm.cc/download), problem temporarily solved while setting "AppNoConsole" to 1 via nssm commandline, and manually "continue" concerned services:
```
C:\neard\core\libs\nssm\nssm.exe set neardapache AppNoConsole 1
C:\neard\core\libs\nssm\nssm.exe set neardmailhog AppNoConsole 1
C:\neard\core\libs\nssm\nssm.exe set neadmemcached AppNoConsole 1
```

Obviously commands must be re-applied if neard restarts.

If you can put correction in next version... :-)

Neard v. 1.0.22
Win 10 Creators Update x64 (v. 1703, build 15063.0)
[Logs here if needed](https://www.sendspace.com/file/qvdpuq)
![Screenshot](https://cloud.githubusercontent.com/assets/7107676/24852026/345d20e4-1dd6-11e7-8d96-ffa46c71e68f.jpg)

**Comment by crazy-max** [comment]
Hi,

It's already implemented for the next release, see issue #239.
Btw thanks for your input ;)

**Comment by dcanl** [comment]
Sorry, didn't well-checked... 

Thanks for update!

**Comment by crazy-max** [comment]
A hotfix has been created for this issue : http://neard.io/news/2017-04-15-service-cannot-start-windows-10-creators-update/

**Comment by svatas** [comment]
I have this issue with the latest Neard 1.4. Symptoms are the same - neardapache service is in State 7

**Comment by cawoodm** [comment]
What does `AppNoConsole` actually mean/do?

**Comment by N6REJ** [comment]
@cawoodm more then you ever wanted to know... https://nssm.cc/
but to answer your question it prevents a "window" from being used.
