### ISSUE TITLE
Unable to switch PHP and Apache

### ISSUE THREAD

**Issue by Hlsgs** [crazy-max/neard#255]
I'm trying to switch to PHP 7, but I can't switch PHP because it's incomaptible with the older Apache and vice-versa, so, basically, there's no way to switch.

**Comment by crazy-max** [comment]
Yes indeed, if you want to switch to PHP 7 and so to Aache 2.4, you have :

* Exit Neard
* In the base `neard/neard.conf`, modify the `apacheVersion` with your 2.4 version.
* In the base `neard/neard.conf`, modify `phpVersion` with your PHP 7 version.
* Start Neard

I will add an entry in the [FAQ](http://neard.io/doc/faq/) for this issue.

**Comment by Hlsgs** [comment]
Works. Thanks for the fast response. I'm still testing Neard and so far so good. Keep up the great work!

**Comment by crazy-max** [comment]
Thanks for your support 👍
