### ISSUE TITLE
Apache 2_4_4 issue with PHP 7_0_17

### ISSUE THREAD

**Issue by eric13500** [crazy-max/neard#256]
Hi

I've got an issue with Apache 2.4.4 when I set PHP on 7.0.17 version (please see snapshot joined).

PHP 7 is needed for Joomla 3.7, so...

Thans for your help !

![neard apache 2_4_4 php 7_0_17 issue](https://cloud.githubusercontent.com/assets/27079634/25808715/39b61ca8-340b-11e7-87e7-34001c48e1d7.PNG)

**Comment by crazy-max** [comment]
Hi, can you try with the latest apache 2.4 ?

**Comment by eric13500** [comment]
Hi

I have already installed the latest versions of the core and of all the modules : 

- Neard 1.2.7
- Apache 2.4.4 r5
- PHP 7.0.17 r15
- PHP 7.1.3 r15
- phpMyAdmin 4p5 r7
- Neard Adminer 4.3.1 r7

Same issue with PHP 7.1.3

Works fine with PHP 5.5.35 r14, but Joomla 3.7 needs PHP 7

**Comment by crazy-max** [comment]
Ok thanks for your feedback!
Have you tried with apache 2.4.25 r5?

**Comment by eric13500** [comment]
Done.

Works fine with Apache 2.4.25 r5 and PHP 7.1.3 r15, But it is version 2.4.4 that is implemented in my webhost...

Your 2.4.25 is the lastest, but not the higher...
Is there something to do ?

**Comment by crazy-max** [comment]
2.4.4 < 2.4.25
Look a the release date in the table : http://neard.io/bins/apache

**Comment by eric13500** [comment]
Sorry for my mistake, and thanks a lot for your answers !

Best regards

**Comment by crazy-max** [comment]
No problem! But there is still an issue with apache 2.4.4

**Comment by eric13500** [comment]
So I reopen issue...

Good luck for the future.

Regards

**Comment by crazy-max** [comment]
Thanks ;)

**Comment by crazy-max** [comment]
This issue is linked to #199

> Infos have been added on the module page of [Apache](http://neard.io/bins/apache/#openssl) and [PHP](http://neard.io/bins/php/#openssl).
> As Apache is on top of PHP (php is loaded as a module for now), Apache OpenSSL version must be equal or greater than OpenSSL version of PHP. I will add a FAQ section about this question.
> If you have other suggestions, do not hesitate.

I will clarify the compatibility on each Aapche and PHP apge on neard.io
