### ISSUE TITLE
Make releases up-to-date

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#264]
Per discussions with @crazy-max I'm creating this issue.
Currently, there are over 18 updates needed to bring the latest release to include the latest releases of all modules.  This is silly.  It's extremely ineffective and counter-intuitive to what's expected.
There should be 2 versions of each release, one with 32bit and one 64 bit.  Considering most machines and operating systems today are 64bit that would be the most important one imo.

**Comment by crazy-max** [comment]
For the moment Neard and all modules are 32bit based, except for MongoDB in the latest version.
I have made a package with the minimal release to ensure backward compatibility, specially for Windows XP users.

But for the next release, support for Windows XP will be drop and i will make multi kinds of releases.

**Comment by crazy-max** [comment]
Here is the modules versions for the next release :

```
bin.apache.version = 2.4.27
bin.filezilla.version = 0.9.60.2
bin.mailhog.version = 1.0.0
bin.mariadb.version = 10.2.7
bin.memcached.version = 1.4.5
bin.mongodb.version = 3.2.12
bin.mysql.version = 5.7.18
bin.nodejs.version = 6.11.2
bin.php.version = 7.1.8
bin.postgresql.version = 9.6.3
bin.svn.version = 1.9.4

app.adminer.version = 4.3.1
app.gitlist.version = 0.5.0
app.phpmemadmin.version = 0.1.0.41
app.phpmyadmin.version = 4p6
app.phppgadmin.version = 5.2
app.webgrind.version = 1.4.0
app.websvn.version = 2.3.3

tool.composer.version = 1.4.2
tool.console.version = 2.00.148.3
tool.drush.version = 8.1.11
tool.ghostscript.version = 9.21
tool.git.version = 2.14.1
tool.hostseditor.version = 1.1.0.0
tool.imagemagick.version = 7.0.5-10
tool.perl.version = 5.26.0.1
tool.phpmetrics.version = 1.9.2
tool.phpunit.version = 5.6.1
tool.python.version = 3.6.0.1
tool.ruby.version = 2.4.1.2.p111
tool.wpcli.version = 0.24.1
tool.xdc.version = 1.0b5
tool.yarn.version = 0.24.6
```
