### ISSUE TITLE
Replace xdebug-client with modern eqv.

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#265]
The last version of xdebug client was in 2009!!  Surely something better has come along since then.
Does it even work with xdebug 2?
Perhaps something like https://github.com/robertbasic/pugdebug would be more useful?

**Comment by crazy-max** [comment]
Yes indeed the XDebugClient module seems to not be maintained but you have the [Webgrind](http://neard.io/apps/webgrind/) module if you want ?
I will take a look at pugdebug to replace the XDebugClient.

**Comment by crazy-max** [comment]
Unfortunately, pugdebug stores the configuration in the registry : `HKEY_CURRENT_USER\Software\pugdebug`

![image1](https://user-images.githubusercontent.com/1951866/27005382-e3c747ea-4e1d-11e7-958c-74566fd9af0a.png)

**Comment by crazy-max** [comment]
@N6REJ

I close this issue for now.
If you find another alternative, open a new issue.
Thanks!
