### ISSUE TITLE
Add one button github / gitlab push

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#269]
Max, how hard would it be to add a 1 button committ/push to gitlap &/or github where it is pushing the entire neard folder?
Running into a few issues with the remote setup we talked about and trying to figure out a intelligent work around.  For whatever reason the users are not syncing even though the tables are.

**Comment by crazy-max** [comment]
Git is not design to be used as a synchronization tool.
You could use rsync for example but i think every synchronization client like Dropbox, OneDrive, Owncloud, etc... should work but only with a manual sync to prevent data corruption (mysql data for example).
I will reopen your sync issue #258 and close this one
