### ISSUE TITLE
replace notepad2-mod with notepad++ portable

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#274]
@crazy-max max,  can we replace notepad2 with notepad++ portable?  If so how?

**Comment by crazy-max** [comment]
@N6REJ Notepad++ is hard to customize for a final user, i have tried before with SublimeText but [Notepad2-mod](https://github.com/XhmikosR/notepad2-mod) is less restrictive.
I can take a new look on Notepad++ and if possible provide an option on Neard to select your favorite text editor.

**Comment by N6REJ** [comment]
I appreciate that.. as I"m sure your aware it and sublime are the kings

**Comment by crazy-max** [comment]
@N6REJ, in the next release notepad2-mod will be removed as a module because it's only used by Neard core to debug Apache, MySQL, etc...
But you can use your own text editor by editing `notepad = "notepad.exe"` in `neard.conf`

**Comment by crazy-max** [comment]
See #314

**Comment by N6REJ** [comment]
right, that works wonderfully.. Thanks for considering inclusion
