### ISSUE TITLE
Release of php 7.0.20 & 7.1.5

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#276]
@crazy-max which version should we download?  I don't know if threadsafe or not.. I'd prefer to use x64

**Comment by crazy-max** [comment]
@N6REJ As stated in the [FAQ](http://neard.io/doc/faq/#phpexe---entry-point-not-found), on Neard **PHP is installed as Thread Safe**.
Apache module is based on x86 architecture unfortunately and PHP is declared as an Apache module but in a future release, PHP will be an independent and declared as a separate service.

**Comment by N6REJ** [comment]
sorry thought I read it fully.. tyvm

**Comment by crazy-max** [comment]
No problem ;)
