### ISSUE TITLE
phpmyadmin won't display nor login

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#277]
@crazy-max sorry to bother you again.  
I updated ALL packages to their latest and added phpmyadmin 4.7.10  
I'm not sure what I did wrong but regardless it's not working perfectly :(
Here is my setup.  Not trying to do anything fancy right now just get it to fully work.
phpmyadmin only displays blank page or it says the server is missing...
[Full updated neard](https://www.amazon.com/clouddrive/share/zyFWeyPM1N4MdkkapQ9rRZdZOn4rM15l8cXT1XIA4G?ref_=cd_ph_share_link_copy)
If it matters I've ran the "create ssl certificate" function because for current testing joomla runs in https always.  
Also, is there a function to create virtual hosts?  If not whats the best procedure.  Everything will be local just multiple installations.
Thanks

**Comment by crazy-max** [comment]
You can create a virtual host here :

![image](https://user-images.githubusercontent.com/1951866/27102039-28f93de2-5084-11e7-80a2-15234401a623.png)

Enter a server name and the destination of your document root. This will create the virtual host configuration and the SSL certificate.

For your problem with phpmyadmin i will take a look on your neard.7z package.

**Comment by N6REJ** [comment]
Pro as always... if it helps I only need one of anything of course.

**Comment by crazy-max** [comment]
A rapid check, why you don't use the official neard module of phpmyadmin ?

![image](https://user-images.githubusercontent.com/1951866/27102760-b8a93300-5086-11e7-8410-a3c474badfe4.png)

Neard provides multi versions of phpmyadmin (4p5, etc...) because of PHP version compatibility :

```
php52 = "4.0.10.20"
php53 = "4.4.15.10"
php55 = "4.7.0"
```
> Example with phpmyadmin4p6

**Comment by crazy-max** [comment]
An other look,

Your `neard.conf`` at the root folder is wrong :

![image](https://user-images.githubusercontent.com/1951866/27103203-317bd9b2-5088-11e7-8a2e-df7a7727d03a.png)

Indeed you don't have a 4.7.0 release in `apps\phpmyadmin` :

![image](https://user-images.githubusercontent.com/1951866/27103218-42d17f8c-5088-11e7-9aa8-c8f910871f91.png)

And as you can see in the phpmyadmin.conf alias, there is a problem :

```
Alias /phpmyadmin "C:/tmp/neard/apps/phpmyadmin//4.7.1/"
```

If i use the 4p6 bundle of phpmyadmin Neard's provides, it works :

![image](https://user-images.githubusercontent.com/1951866/27103364-ad5c1e5c-5088-11e7-9c66-35c0b587a9da.png)


![image](https://user-images.githubusercontent.com/1951866/27103341-9b9a369a-5088-11e7-8fc3-7b1583c5e958.png)

**Comment by crazy-max** [comment]
I close the issue waiting your response thanks!

**Comment by N6REJ** [comment]
sorry for delay @crazy-max I tried 4x yesterday to leave a reply and my damn system kept BSOD on me.. 8x in 2hrs *ARGH*
Anyway, your change to 4p6 fixed phpmyadmin, so tyvm!!!
as for phpmyadmin.conf  I'm not sure where you found that and I know I didn't touch it.  I find it interesting that the drive is specified.
Lastly I again want to thank you for being so responsive and kind.  I hope ultimately I'm helping make neard stronger not just being a nuisance.
