### ISSUE TITLE
Bit Defender alert

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#278]
just had a interesting alert from bit defender..
![image](https://user-images.githubusercontent.com/1850089/27158152-0f08ab3c-512b-11e7-8a1f-c7f5bc26ce67.png)

**Comment by crazy-max** [comment]
Thanks, i have opened an issue on the official repository.

**Comment by N6REJ** [comment]
@crazy-max be aware, on doing fresh install of 1.2.16 bitdefender marked as potentially harmful & deleted neard.exe and C:\neard\core\libs\nssm\nssm.exe and when i told it to exclude them they were NOT restored and could not be until I rebooted the system.

**Comment by crazy-max** [comment]
@N6REJ MMhhh very strange, neard.exe does not move since the beginning. Maybe a new signature has been added to bitdefender. Can you check with Neard 1.2 please ?

**Comment by N6REJ** [comment]
![image](https://user-images.githubusercontent.com/1850089/28745516-74d6b54e-743f-11e7-8c34-660be6fbfd46.png)
what I find strange is it didn't complain about THOSE 2 files in 1.2.11 but did throw a trojan error if you recall, but in 1.2.16 no trojan error but it threw the application error but NOT on extract.. it didnt' do it till I ran it.
And sure enough.. once I ran 1.2 it threw it
![image](https://user-images.githubusercontent.com/1850089/28745552-284323d8-7440-11e7-8ea8-6c3ea45db44e.png)

**Comment by N6REJ** [comment]
ok, bit defender is now pulled from my system.  It threw c:\desktop\neard\neard.exe away permamently, which is fine, BUT, at the same time it threw c:\neard\neard.exe away which is NOT fine, as it had already been excluded!!!  .. bad bad bad boy! 👎

**Comment by crazy-max** [comment]
Based on VirusTotal analysis, there is no threats :

* `neard.exe` : https://www.virustotal.com/en/file/bed8eeffb63e893b1053fb4ca3a73e24a4e659face21589045165d3238770e11/analysis/
* `core/libs/nssm/nssm.exe` : https://www.virustotal.com/en/file/472232ca821b5c2ef562ab07f53638bc2cc82eae84cea13fbe674d6022b6481c/analysis/

But for MailHog 1.0.0 there are threats : https://www.virustotal.com/en/file/0c0e85b6e66e8f43318a298531a9a9d8aad98ef77744042f7c3049970bb57e42/analysis/

Can you send me VirusTotal reports (via https://www.virustotal.com) for `neard.exe` and `core/libs/nssm/nssm.exe` ?

Thanks

**Comment by N6REJ** [comment]
[Nerd](https://www.virustotal.com/en/file/bed8eeffb63e893b1053fb4ca3a73e24a4e659face21589045165d3238770e11/analysis/1501365644/)
[nssm](https://www.virustotal.com/en/file/472232ca821b5c2ef562ab07f53638bc2cc82eae84cea13fbe674d6022b6481c/analysis/1501365129/)
[mailhog 1.0.0](https://www.virustotal.com/en/file/0c0e85b6e66e8f43318a298531a9a9d8aad98ef77744042f7c3049970bb57e42/analysis/1501365385/)

yet bitdefender has been allowing neard to run for a month now... WAY NOT COOL

**Comment by N6REJ** [comment]
maybe we should replace mailhog ??  http://www.philbertphotography.com/blog/own-smtp-server

**Comment by crazy-max** [comment]
I prefer to stay on an open source stacks.
I close this issue, it's a false positive (see mailhog/MailHog#154)
