### ISSUE TITLE
Request Git Bundle 2.13.2

### ISSUE THREAD

**Issue by freMea** [crazy-max/neard#279]
This last bundle comes with Git Flow 1.11. Currently, the neard version has an old version of git flow that comes with git 1.13.0.

**Comment by crazy-max** [comment]
@freMea You mean 2.13.2 ;)

**Comment by crazy-max** [comment]
Available here : http://neard.io/tools/git/#releases
If you want to be notified of new releases of Git bundles, you can star the repository : https://github.com/crazy-max/neard-tool-git
