### ISSUE TITLE
phpmyadmin fails to start with unstable release

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#281]
@crazy-max hey max, just installed your "unstable release" version.  The only thing I've updated is php ( your 7.1.7 bundle ) , upon starting phpmyadmin I get
![image](https://user-images.githubusercontent.com/1850089/27997727-4dda47d8-64c4-11e7-9236-768dff8927de.png)
I renamed the bundle to and removed the "-" which then threw red triangles for php and apache.
updating apache to 2.4.5
resulted in 
![image](https://user-images.githubusercontent.com/1850089/27997808-984f32d2-64c5-11e7-80cd-84778278b883.png)
switching back to 5.3.13 results in 
![image](https://user-images.githubusercontent.com/1850089/27997819-da9f11c0-64c5-11e7-97ea-728844e9ea85.png)
Let me know what I can do to help resolve stuff

**Comment by N6REJ** [comment]
update: copying 5.3.13's neard.conf to 7.1.7 resulted in both apache and php starting, but there is no php.neard nor php.ini in 7.1.7

**Comment by crazy-max** [comment]
Hi,

I've download the latest PHP 7.1.7 from Neard web site, everything is fine for me and there is a php.ini in the php7.1.7 folder:

![image](https://user-images.githubusercontent.com/1951866/27997942-c2d6788e-6502-11e7-9342-3b38e12c72b6.png)

* How do you switch from PHP 5.3.13 7.1.7 ?
* What is you Neard version ?
* You talk about `updating apache to 2.4.5`. Where do you find Apache 2.4.5 ?
* And can you follow and apply these instructions as it is said when you create an issue please : http://neard.io/doc/reporting-issue/

**Comment by crazy-max** [comment]
I've download the latest unstable Neard 1.2.11 and the modules, PHP 7.1.7 and Apache 2.4.25 then :

* Extract Neard 1.2.11
* Extract Apache 2.4.25 to `bins\apache`
* Extract PHP 7.1.7 to `bins\php`
* Edit `neard.conf` in the root folder and change modules versions for apache and php.
* Execute `neard.exe`

Following these steps, everything works fine.

**Comment by N6REJ** [comment]
something is weird... I'll redo it after lunch ( 45min? )
![image](https://user-images.githubusercontent.com/1850089/27998164-129f4754-64ce-11e7-9178-46bdcf7e2410.png)
7.0.19 works.

**Comment by crazy-max** [comment]
The folder structure of your PHP 7.1.7 is not the same as the official Neard module PHP 7.1.7.
Where do you download it ??

**Comment by N6REJ** [comment]
I was going to just use windows LAMP stack and then changed my mind and apparently extracted 7.1.7 onto the desktop instead of in a folder... installed the proper neard bundle and that problem went away.. LOTS of red triangles but since its unstable release I'm not surprised.
As for reporting I apologize and will follow the directions more carefully.
