### ISSUE TITLE
vhosts

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#282]
@crazy-max is there any documentation explaining the vhosts folder?
whats the difference between putting the files in www vs vhost?

**Comment by crazy-max** [comment]
Hi,

No there is no documentation on the Neard website explaining the vhosts functionnality. You have to be familiar with Apache to understand that. Here are some links about that :

* https://httpd.apache.org/docs/2.4/vhosts/
* http://foundationphp.com/tutorials/apache_vhosts.php

If you are familiar with Linux environment, on Neard `www` reflects `/var/www` on your server and `vhosts` can be `/etc/apache2/sites-available`.
