### ISSUE TITLE
Add Visual C++ Redistributables 2017 (VC15)

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/neard#283]

**Comment by crazy-max** [comment]
Available : https://github.com/crazy-max/neard-prerequisites/releases/tag/r9

**Comment by N6REJ** [comment]
@crazy-max I'm concerned about installing r9 when there are 2 updates for windows xp/7  included and yet I'm on windows 10 x64 pro
- KB838079 : Integrated for Windows XP to install Windows Support Tools.
- KB2731284 : Fix "33" DOS error code when memory memory-mapped files are cleaned by using the FlushViewOfFile() function in Windows 7.

**Comment by crazy-max** [comment]
KB838079 is only installed if Windows XP is detected : https://github.com/crazy-max/neard-prerequisites/blob/master/setup/setup.iss#L111
Same for KB2731284 if Windows 7 is detected : https://github.com/crazy-max/neard-prerequisites/blob/master/setup/setup.iss#L99

**Comment by N6REJ** [comment]
ok, cool.. ty!

**Comment by crazy-max** [comment]
Yep the app is not signed for the moment

**Comment by N6REJ** [comment]
does it install only 32bit or both?  I vaguely remember reading on ms visual stuff that x64 is needed?

**Comment by crazy-max** [comment]
;)
