### ISSUE TITLE
Release of Node.js 4.8.4, 6.11.1, 7.10.1, 8.1.4

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/neard#285]

**Comment by crazy-max** [comment]
Available : http://neard.io/bins/nodejs/#releases

**Comment by N6REJ** [comment]
@crazy-max they just released several updates since the 11th.. apparently there are some security fixes.

**Comment by crazy-max** [comment]
@N6REJ Yep that's why i released the latest versions of Node.js pretty fast for Neard

**Comment by N6REJ** [comment]
sorry, should have clarified, they are at 8.2.1 now LOL
