### ISSUE TITLE
Error Installing PHP_CodeSniffer via pear

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#292]
Hi Max, so I've got an issue that might warrant two tickets..
I'm trying to install codesniffer and I'm running into a major bug.  I'm not sure that its neard related but I thought I'd bring it to you to see what your thoughts/fix is.
OS: Windows 10 x64 pro
Neard: 1.2.11
php 5.6.30, php 7.0.19 & php 7.1.7 all with same result
[Log files](https://drive.google.com/open?id=0B31YVf0qLc5gc2JaZk9mNHN4enc)
screen capture: [php-codesniffer-screen-capture.txt](https://github.com/crazy-max/neard/files/1152143/php-codesniffer-screen-capture.txt)  

You'll notice an xdebug error that I've not been able to figure out but idk if that's relevant or not.

**Comment by crazy-max** [comment]
Hi @N6REJ,

Can you type `phpcs --version` and give me the output ?
I have the same error as you but PHPCS has still installed.

**Comment by N6REJ** [comment]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>f:

F:\>cd neard

F:\neard>phpcs --version
PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0

Warning: Xdebug MUST be loaded as a Zend extension in Unknown on line 0
PHP_CodeSniffer version 2.8.1 (stable) by Squiz (http://www.squiz.net)

F:\neard>

**Comment by N6REJ** [comment]
I think I found part of the problem.. it seems php's path doesn't get changed when version is changed..
![image](https://user-images.githubusercontent.com/1850089/28740610-9862dccc-73cc-11e7-8239-9d34e8098ad8.png)
Reload and restart all services have no effect.

**Comment by N6REJ** [comment]
Fixed in release [1.2.16}(https://github.com/crazy-max/neard/releases/tag/v1.2.16)
NOTE:  The reason xdebug throws error is if you go to php-extensions and activate the module it clashes with the hard coded xdebug statement already in .php.ini when neard is installed.
with php_xdebug module deactivated it infact still has xdebug active as can be seen in phpinfo
![image](https://user-images.githubusercontent.com/1850089/28741800-5ede780e-73e4-11e7-9bfb-6f75934903b7.png)
infact, the xdebug extension doesn't even show up in the extension matrix
![image](https://user-images.githubusercontent.com/1850089/28741806-969ce492-73e4-11e7-8398-1fb4b19bff89.png)

**Comment by crazy-max** [comment]
Your PHP path is not changed because you have the smae cmd opened between the previous and current version of PHP. You have to open a new cmd to reflect the new environment variables.

Concerning xdebug, indeed there is an issue, i have to exclude php_xdebug for the extensions php within the Neard menu.
