### ISSUE TITLE
Mysql Issues

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#297]
There are a couple of mysql issues with the latest 1.2.16 release.
1) index.php shows that mysql service is stopped even when running
2) can't start mysql 5.7.19
![mysql-5 7 19](https://user-images.githubusercontent.com/1850089/28741707-182fcd24-73e2-11e7-9a53-535a6d6924e8.PNG)
[logs](https://drive.google.com/open?id=0B31YVf0qLc5gc2JaZk9mNHN4enc)
ONLY neard objects have been used.  This is a clean installation with only the data folder, vhosts & www being kept from 1.2.11
all root www files were replaced with the 1.2.16 versons

**Comment by crazy-max** [comment]
No issue for me here :

* Extract neard 1.2.16
* Extract mysql 5.7.19 r10 in `bins\mysql`
* Start Neard
* Switch MySQL 5.5.24 to 5.7.19
* Restart Neard

![image](https://user-images.githubusercontent.com/1951866/28744512-f172fad6-7462-11e7-9ccc-fe24072d70da.png)

In your logs i saw in `neard-error.log` :

```
[2017-07-28 22:10:34] E_WARNING mysqli_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: NO) in /core/classes/bins/class.bin.mysql.php on line 167
  #1  mysqli_connect(127.0.0.1:3306, root, ) called at [C:\neard\core\classes\bins\class.bin.mysql.php:167]
  #2  BinMysql->checkPort(3306) called at [C:\neard\core\resources\homepage\ajax\ajax.mysql.php:16]
  #3  include(C:\neard\core\resources\homepage\ajax\ajax.mysql.php) called at [C:\neard\core\resources\homepage\ajax.php:24]
```

Note : if you changed your MySQL root password from Console or PhpMyAdmin, it will not be changed for Neard. You have to change the root password within the Neard menu :

![image](https://user-images.githubusercontent.com/1951866/28744526-31b966c0-7463-11e7-9bb7-1136e2c74bbe.png)

And looking to `logs\archives\2017-07-28-220411\neard-error.log` there are some errors switching mysql 5.5.24 to 5.7.19 :

```
[2017-07-28 22:03:59] E_WARNING file_get_contents(N/A/mysql/mysql5.5.24/neard.conf): failed to open stream: No such file or directory in /core/classes/bins/class.bin.mysql.php on line 104
  #1  file_get_contents(N/A/mysql/mysql5.5.24/neard.conf) called at [C:\neard\core\classes\bins\class.bin.mysql.php:104]
  #2  BinMysql->replaceAll(Array ([mysqlPort] => 3306)) called at [C:\neard\core\classes\class.module.php:56]
  #3  Module->replace(mysqlPort, 3306) called at [C:\neard\core\classes\bins\class.bin.mysql.php:482]
  #4  BinMysql->setPort(3306) called at [C:\neard\core\classes\bins\class.bin.mysql.php:139]
  #5  BinMysql->changePort(3306) called at [C:\neard\core\classes\actions\class.action.switchVersion.php:157]
  #6  ActionSwitchVersion->processWindow(56389464, 1002, 56389464, 0, 0)
  #7  call_user_func_array(Array ([0] => ActionSwitchVersion Object ([] => Splash Object ([] => 56389464,[] => 1,[] => 1,[] => Array ([0] => 1001,[1] => 56382960),[] => ),[] => 5.5.24,[] => BinMysql Object ([] => Win32Service Object ([] => neardmysql,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ),[] => C:/neard/logs/mysql.log,[] => C:/neard/bin/mysql/mysql5.7.19/bin/mysqld.exe,[] => C:/neard/bin/mysql/mysql5.7.19/my.ini,[] => 3306,[] => root,[] => ,[] => C:/neard/bin/mysql/mysql5.7.19/bin/mysql.exe,[] => C:/neard/bin/mysql/mysql5.7.19/bin/mysqladmin.exe,[] => bins,[] => mysql,[] => MySQL,[] => 5.5.24,[] => r10,[] => N/A/mysql,[] => N/A/mysql/mysql5.5.24,[] => ,[] => N/A/mysql/mysql5.5.24/neard.conf,[] => ),[] => 5.7.19,[] => 1,[] => Win32Service Object ([] => neardmysql,[] => Neard MySQL 5.7.19,[] => C:\neard\bin\mysql\mysql5.7.19\bin\mysqld.exe,[] => neardmysql,[] => 3,[] => 1,[] => ,[] => 0,[] => 424),[] => 1,[] => Array ([C:/neard/bin/mysql] => Array ([0] => my.ini)),[] => Switch MySQL version 5.5.24),[1] => processWindow), Array ([0] => 56389464,[1] => 1002,[2] => 56389464,[3] => 0,[4] => 0)) called at [C:\neard\core\classes\class.winbinder.php:463]
  #8  __winbinderEventHandler(56389464, 1002, 56389464, 0, 0, 0)
  #9 wb_main_loop()
  #10 call_user_func_array(wb_main_loop, Array ()) called at [C:\neard\core\classes\class.winbinder.php:73]
  #11 WinBinder->callWinBinder(wb_main_loop) called at [C:\neard\core\classes\class.winbinder.php:123]
  #12 WinBinder->mainLoop() called at [C:\neard\core\classes\actions\class.action.switchVersion.php:107]
  #13 ActionSwitchVersion->__construct(Array ([0] => MySQL,[1] => 5.5.24)) called at [C:\neard\core\classes\actions\class.action.php:67]
  #14 Action->process() called at [C:\neard\core\bootstrap.php:19]
```

You hve removed MySQL 5.5.24 before siwtching to 5.7.19 that's why you have the MySQL service start error.

**Comment by N6REJ** [comment]
I didn't change passwords at all.  Nor have I removed either version of mysql.  Infact, I removed 5.7.19 and redownloaded and replaced it.  I don't know what the N/A/ means but its no path that I have.
https://drive.google.com/file/d/0B31YVf0qLc5gUXlaSjdtRXZBclU/view  This video will show you some of whats going on.. sorry the webcam was in the way :(
I'll upload my install to googledrive as soon as I reboot.

**Comment by crazy-max** [comment]
Ok zip and upload your Neard installation i will take a look

**Comment by N6REJ** [comment]
btw, its not mailhog, its lsass.exe... talking to ms and will upload everything to the same google folder.. one sec.

**Comment by N6REJ** [comment]
just did a full reboot and now even though lsass.exe is running its NOT using port 3306. It's using
  TCP    [::]:49731             BearsPC:0              LISTENING
 [lsass.exe]  I haven't restarted neard and will wait for you.  If you want to zoom I'm open to it.
the dang file FINALLY uploaded https://drive.google.com/drive/folders/0B31YVf0qLc5gc2JaZk9mNHN4enc?usp=sharing  gave you some extra info also.

**Comment by N6REJ** [comment]
@crazy-max any word on fixing this?

**Comment by crazy-max** [comment]
@N6REJ Oh sorry i forgot to take a look! And i lost your upload :/
Can you upload it again ?

**Comment by N6REJ** [comment]
Sorry for stupid long delay, apparently i forgot just as you did LOL.. this is as of yesterday.
https://drive.google.com/open?id=0B31YVf0qLc5gMHNReXlRRTNaRWM

**Comment by N6REJ** [comment]
@crazy-max even with the new update I'm still having that same silly mysql issue.. I simply can't upgrade it and I still get the not running when it is error.. here's the zip 
https://drive.google.com/file/d/0B31YVf0qLc5gMHNReXlRRTNaRWM/view?usp=sharing

**Comment by crazy-max** [comment]
Hi @N6REJ, sorry for the delay, i'm really busy this time !
For your issue, i think it comes from your upgrade process.
Neard really needs a setup instead of an archive for the upgrade process, I will work on it for the next release.
I will give you an answer in the other issue

**Comment by N6REJ** [comment]
ok... ty.

**Comment by N6REJ** [comment]
@crazy-max just an update.. I just did a complete and total wipe of neard, unzipped to the same c:\neard folder and started neard.. immediately the mysql error came up.
![image](https://user-images.githubusercontent.com/1850089/32410747-32931520-c196-11e7-941b-e1b2678265c2.png)
nothing significant was changed in neard.conf
`; -- SETTINGS

lang = "english"
timezone = "America/Chicago"
notepad = "C:\Program Files\Notepad++\notepad++.exe"
maxLogsArchives = "50"
logsVerbose = "2"
scriptsTimeout = "120"

;========================
; No edits necessary beyond this line.
; If you made some changes, you have to reload and/or restart Neard.
;========================

; -- MAIN

defaultLang = "english"
hostname = "BearsPC"
browser = "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
online = "0"
launchStartup = "0"
`
I turned off several modules but didn't change anything.

**Comment by N6REJ** [comment]
pretty sure this is the cause..
![image](https://user-images.githubusercontent.com/1850089/32410822-f6f2437c-c197-11e7-9156-19e004c33b50.png)

**Comment by N6REJ** [comment]
ok, I've fixed everything, the issue is that when neard is put in c:\ then you need to turn off "read only" and change the permissions to full control for users and authenticated users.

**Comment by crazy-max** [comment]
Thanks for pointing this out, 8 will check this permission issue

**Comment by N6REJ** [comment]
it only seems to come into play when neard is put in root.
