### ISSUE TITLE
SSH Certs created for wrong country

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#302]
looks like when you ask nerd to create a SSH cert its using the default wamp country of france.
![image](https://user-images.githubusercontent.com/1850089/28769841-bb29f39e-75a2-11e7-8025-6c9678c3f82e.png)

**Comment by crazy-max** [comment]
SSH certificates are created only for testing and development purpose. So there is no need to choose / change the default country based on Neard.
