### ISSUE TITLE
New launch manager

### ISSUE THREAD

**Issue by StaggerLeee** [crazy-max/neard#303]
Did you see this menu launch manager ?
Does a licence fit Neard platform ?

As I see it after some playing it could be perfectly used for Neard. And give us Users unlimited customization possibilities too.

https://www.ugmfree.it/Default.aspx

Besides basic Neard using, you could limit their lists of GPL portable Apps to few/some of them web developers use often. And if any Neard User wish he/she can install it and use it thru manager.

Some of them that can be left on list and given Users as optional one click install (they are GPL):

- AS Password generator
- Bluelife hosts editör
- BowPad code editor
- There are backup and sync GPL few tools
- FileZilla FTP client
- HeidiSQL
- Master Password(s) GPL tool
- Link checker
- Notepad 2, Notepad ++
- Some from Nirsoft Suite, some from Systernals Suite.

Those Apps at side, this menu launcher is very easy to customize.
Second good thing compared to present one is pleasant design, modern look, regularly updated, and support forum too.
And many other improvement compared to present one. That can be used or not, taste thing.

**Comment by crazy-max** [comment]
Hi @StaggerLeee,

It could be a good idea but unfortunately SyMenu is not opensource.
I'm working on a huge refactoring of Neard (2.0) but it takes time and I do not have much :smile:

Anyway thank you for your contribution and do not hesitate to propose new ones!
