### ISSUE TITLE
Git security update & keygen 

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#305]
@crazy-max Sorry to bother you max but thought I'd like you know that there has been a security update for git and that you can't run the "ssh-keygen" function from within neard git console.  You can run it just fine from windows git bash.
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

Here's the security release info.. http://marc.info/?l=git&m=150238802328673&w=2
and I created the [folder for 2.14.1 x64](https://drive.google.com/file/d/0B31YVf0qLc5gWmVBeTBqMnlkdmM/view?usp=sharing) for neard incase your interested in it.

**Comment by crazy-max** [comment]
@N6REJ Ok thanks i will make a new release for the Git module!

**Comment by crazy-max** [comment]
See issue #306

**Comment by N6REJ** [comment]
the zip i gave you works fine for x64

**Comment by crazy-max** [comment]
Yes i see that thanks but the module has to be built and included in neard-modules-untouched and neard-tool-git repositories to make it available for everyone.
For more info, check this link : http://neard.io/doc/contribute/
