### ISSUE TITLE
Can't change apache and php version

### ISSUE THREAD

**Issue by tienv2i** [crazy-max/neard#307]
I am have just used neard recently. Now, I want to change version of apache to 2.4.24 and php to 5.6.30 but it failed. I download apache from http://neard.io/bins/apache/ and php from http://neard.io/bins/php/ then I extract them to neard\bin\php and neard\bin\apache. After that, I restart neard and change apache version form neard menu, it said that appache version doesn't seem to be compatible with php 5.3.13. When I change php to v5.6.30, it said that php version  doesn't seem to be compatible with apache 2.2.22.
so How can I change php and apache verion?

**Comment by crazy-max** [comment]
Hi @tienv2i,

As you can see in the [compatibility table](http://neard.io/bins/apache/#compatibility-table), Apache 2.4 is compatible for PHP >= 5.4. But you cannot switch to Apache 2.4 with PHP 5.3.13. You can switch first to PHP 5.4 then switch Apache to 2.4 then switch PHP 5.6.

Or you can edit your neard.conf file and change :

`apacheVersion = "2.2.22"` to `apacheVersion = "2.4.24"`
and `phpVersion = "5.3.13"` to `phpVersion = "5.6.30"`
then start Neard.
