### ISSUE TITLE
Firefox & Chrome require the subjectAltName (SAN) X.509 extension for certificates

### ISSUE THREAD

**Issue by StaggerLeee** [crazy-max/neard#308]
Does it work with localhost without need to make virtual hosts ?

Chrome gives error "This server could not prove that it is localhost; its security certificate does not specify **Subject Alternative Names**. This may be caused by a misconfiguration or an attacker intercepting your connection.", 

as certificate is made for Linux, not WIndows.

PS: I know it can appear stupid to have it on isolated localhost. Just testing new Google Pagespeed before website goes live. Chrome now has new Google extension for Pagespeed allowing localhost testing.
https://developers.google.com/web/tools/lighthouse/

**Comment by N6REJ** [comment]
yeah, works fine.. let me know if you need help

**Comment by StaggerLeee** [comment]
Help need I, any.
Would someone be nice to write short step by step how to activate it. Chrome detect it is not encrypted connection. So I obviously cannot make it to work.

**Comment by N6REJ** [comment]
all that means is you need to tell it yes, and then add exception for self certificate.. totally normal

**Comment by StaggerLeee** [comment]
You are a man of big and long words. :)

I will buy you a beer if you treat me like beginner and explain what I have to do to make it work. Namely, it is first time I need it, as strange as it may sound.

Put all my websites on one shared hosting without SSL, what I will of course not do anymore due to the Google demands. And simply did not use it before.

Checked a bit how it is done in Wamp. Just write few points as list what to do to make it work, ex..
- Start Neard
- Click here
- Click there
- Edit windows hosts file (!!??)
- Etc...

What I have done, and yet Chrome warns it is not encrypted.

- Made SSL certificate in Neard. Tried with different namings, made even several
- Added lines in .htaccess to force URLs to https
- Set WordPress both settings for web address to https
- Vivaldi and Chrome browsers warn it is not secure connection

**Comment by StaggerLeee** [comment]
I mean I do not see anywhere in browsers where to tell it "yes" and "add exception" for certificate. Maybe I did missunderstand.

**Comment by StaggerLeee** [comment]
Subject Alternative Names is missing from Neard certificate. (NET::ERR_CERT_COMMON_NAME_INVALID
)

http://www.expta.com/2017/06/fix-for-certificate-error-in-chrome.html

**Comment by StaggerLeee** [comment]
Looks like encrypted communication and SSL is working. Just this SAN problem, making it difficult to know what site is using https, what not. Browsers will give red triangle for all websites.

I do not know if it is in power of Neard (OpenSSL) to make it work on localhost, and as a certificate not in any trusted lists around the world.

Developer of Neard can explain it best.

**Comment by crazy-max** [comment]
Hi @StaggerLeee,

I have checked on Chrome 60.0.3112.101 and i dont have your `NET::ERR_CERT_COMMON_NAME_INVALID` error :

![image](https://user-images.githubusercontent.com/1951866/29456964-406d74b2-8418-11e7-9bd6-575943fe7d66.png)

What is your Chrome version ?
Have you tried to regenerate the SSL certificate ? (Through Neard > Tools > Generate SSL certificate  whith Name = localhost)

Also please read the [support guidelines](https://github.com/crazy-max/neard/blob/master/.github/SUPPORT.md) and give me your logs and other necessary information.

**Comment by StaggerLeee** [comment]
Hi Max

yes I tried with different names and localhost name only. Target I did not touch, once only as test.
Kaspersky is forcing its own localhost certificate for SSL scanning. I disabled this option, Neard certificate shows with same "error" message.

I activated certificate link in chrome flags, to be able to know what certificate Chrome calls on page(s).

Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by crazy-max** [comment]
Ok thanks, i will investigate on it.

**Comment by crazy-max** [comment]
@StaggerLeee, What is your Apache version ?

**Comment by crazy-max** [comment]
Ok thanks, i will investigate on it.

What is your Apache version ?

Can you attach these files to this issue please :

![image](https://user-images.githubusercontent.com/1951866/29458210-4b8f6c64-841e-11e7-8cf4-7cb445347f59.png)

**Comment by crazy-max** [comment]
As of Chrome 58 it no longer accepts self-signed certs that rely on `Common Name`: 
Instead it requires using `Subject Alt Name`.

**Comment by N6REJ** [comment]
Maybe https://letsencrypt.org/ is a valid option?  I know it works well on our live servers.

**Comment by StaggerLeee** [comment]
Hi Max. Do you still need those files ?

- Apache = 2.4.23
- Windows 10 with latest updates
- Chrome = Version 60.0.3112.101 (Official Build) (64-bit)

F12 and open Chrome developer tool. You will see that your certificate works, https is encrypted. Just to remove that warning triangle, makes it difficult to know what is encrypted and what not.

Not so urgent as any communication is anyway from and to safe localhost and own computer, nothing is live.

It is not needed for anything except testing and new Google Pagespeed testing.

For other Neard users one advice. Inside Chrome use chrome://flags/#show-cert-link to enable link to certificate. This way you will know directly what certificate is called and responsible to website you are on. Left click on icon left in address bar and use Certificate link.

**Comment by crazy-max** [comment]
@N6REJ  Letsencrypt cannot be used for a local environment. Apache has to be "live".

@StaggerLeee No thanks i've got everything I need. Btw, when you have created this issue, have you seen the warning message about support and contributing guidelines?

**Comment by StaggerLeee** [comment]
I missed it, see it now. Looks like some help Info how to use Github.
Do you need those files from core/temp ?

Here is F12 tools, Security tab content. Encryption works, certificate is rejected.

> This page is not secure (broken HTTPS).
> Subject Alternative Name missing
> The certificate for this site does not contain a Subject Alternative Name extension containing a domain name or IP address.
> View certificate
> Certificate error
> There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).
> View certificate
> Secure connection
> The connection to this site is encrypted and authenticated using a strong protocol (TLS 1.2), a strong key exchange (ECDHE_RSA with P-256), and a strong cipher (AES_128_GCM).
> Secure resources
> All resources on this page are served securely.

**Comment by crazy-max** [comment]
@StaggerLeee Thanks i've got everything i need.

**Comment by crazy-max** [comment]
On the next release, certificate will have 2 `subjectAltName` (ex. `*.test.local` and `test.local`).
For `NET::ERR_CERT_COMMON_NAME_INVALID` i have added some information in the FAQ : http://neard.io/doc/faq/#neterr_cert_authority_invalid-since-chrome-58

**Comment by N6REJ** [comment]
I wonder if certutil can be autoran when cert is created?

**Comment by crazy-max** [comment]
Certutil is an interactive command and i prefer let the user choose the method because :
* It is not a portable behavior
* I do not want to add certificates to the user store arbitrarily

**Comment by StaggerLeee** [comment]
I made it to work somehow. After making certificates import them in Trusted Root Certification Authorities. Type "manage computer certificates" in Windows search to find tool.

Were making some changes in SSL Neard config file, and right after this got it to work and be accepted. Uncommented and activated some lines for AltName(s). Do not know if SSL cache in Chrome, Windows played some games, or not. Anyway I will get chance after one month to repeat all process.

**Comment by StaggerLeee** [comment]
it is still not working with 1.3 version.
Is this line correct ?

> private_key	= $dir/private/cakey.pem# The private key

Anyway. even if I make space after .pem it is the same, certificate old problems.

Now with 1.3 version I have problem accessing https Mailhog (1.0.0) panel. http is OK but with several of console errors. Sometimes different, but mostly:

> http://localhost:8025/api/v2/jim 404 (Not Found) angular-1.3.8.js

There is nothing I can see and troubleshoot when all is called from .exe file.

**Comment by StaggerLeee** [comment]
OK, SSL kind of work.  did again as advised, added via console cert to Windows. Strange it lost certificate that worked yesterday, when 1 month is not passed. I remember right dates, and working certificate was one day old. But forget that for now.

https Mailhog gives **ERR_SSL_PROTOCOL_ERROR** regardless if cert for localhost works or not.
I do not use https for mailhog, and do not need it. I am the only one accessing it and is not live on Net.
Just reporting it for you to be aware of it.

Same console error(s) for http Mailhog remain.

**Comment by crazy-max** [comment]
Hi @StaggerLeee,

MailHog have is own HTTP server and is not related to Apache server on Neard.
I suggest to open an issue on their [official repository](https://github.com/mailhog/MailHog).
But maybe there is an issue after adding the localhost cert to the Trusted Root Certification Authorities.
Can you remove the certificate from the Trusted Root Certification Authorities, restart Neard and your browser and try again ?

For your others questions :

> private_key = $dir/private/cakey.pem# The private key
Yes this does not change anything to add a space after .pem

> Uncommented and activated some lines for AltName(s)
Don't understand this part, can you explain plz ?
