### ISSUE TITLE
Upgrade to OpenSSL 1.1.0f

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/neard#309]

**Comment by Julienh** [comment]
Hello,

Any update about upgrading OpenSSL please ?
I have this error when I try to connect to a DB with SSL : 
`SSL operation failed with code 1. OpenSSL Error messages: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version`

I think it is because of the version.
Thank you.
