### ISSUE TITLE
upgrading instructions

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#330]
@crazy-max I'm a bit confused on the upgrading instructions...
![image](https://user-images.githubusercontent.com/1850089/30516988-5fad4cc6-9b15-11e7-99ea-59960f3cd04f.png)
what do you mean by these 3?
remove core from existing I assume and replace with git version?
copy folder from where to where?
is it possible to do a git pull and have it update that way?

**Comment by crazy-max** [comment]
Hi,

> Remove then replace folder `core`

Remove in your current Neard installation the core folder . Then copy the core folder from the .7z archive (not Git!)

> Remove then replace file `sprites.dat`

Same as core one

> Copy folder `tools\ghostscript`

Copy the folder `tools\ghostscript` from the .7z archive to the exact place in your Neard installation.
`neard-1.3.7z\tools\ghostscript` -> `neard\tools\ghostscript`

**Comment by N6REJ** [comment]
ok, thanks for the clarification.

**Comment by N6REJ** [comment]
well, I followed instructions but on instinct I started checking other folders ( like mysql, php ) and sure enough several of the folders had updated versions.
I don't know if my solutions was right, but I wound up, after doing the update shown here http://neard.io/doc/upgrade-notes/ copying everything from c:\neard ON TOP of neard 1.3.25 on my desktop then copying that back into c:

**Comment by crazy-max** [comment]
Hi @N6REJ 

You should never overwrite your current installation with the full directory, which is why there are specific instructions for upgrade.

**Comment by N6REJ** [comment]
I didn't exactly... i followed update process then copied my existing install OVER the upgrade so I would pickup the numerous upgraded packages.  Then moved THAT onto the original files.

**Comment by crazy-max** [comment]
Ok and do you have any issue today?

**Comment by N6REJ** [comment]
still have the mysql issue.

**Comment by crazy-max** [comment]
Hi @N6REJ, i will take a look asap, i still have your archive ;)

**Comment by N6REJ** [comment]
Thanks Max
