### ISSUE TITLE
neard fails to restart on system restart

### ISSUE THREAD

**Issue by iansebryk** [crazy-max/neard#331]
this has been an issue for me for a while, but now that i am busier, its slowly driving me crazy.  whenever i reboot/shutdown the system, when the sytem comes back up (either via startup folder or manually), neard will try to start, burp, throw up a dialog and need to be manually restarted, at which point, on the second launch, it fires up without issue.  as i am having to restart my system often, this has become very irritating.  i know i had reported this a while ago, but was unable to locate the issue, i apologize.  at least here, you have a fresh set of logs to comb through (you had nothing else on your plate, right??  lol).

here is the screenshot belows and a [link to the logs](https://drive.google.com/file/d/0B8YzV8tK9yq6WWxVZmtNRHU3TVk/view?usp=sharing).
![neardstartupreboot](https://user-images.githubusercontent.com/1943574/30565766-d366fd48-9c86-11e7-9018-3f2dc283af58.PNG)

as always, thank you so much for a fabulous product.  indispensible!  :)

EDIT:  note to viewers, the screenshot DOES NOT reflect the version i am currently running, which is 3.1.  i just have been having this problem for a while....  :P

**Comment by N6REJ** [comment]
your using an older version of neard.. The only time neard asks to restart for me ( 1.2.x ) is when there has been a change of some kind.  Have you tried right clicking on neard and using "launch on windows startup" yet?

**Comment by iansebryk** [comment]
nope.  i'm using the latest version.  just upgraded last week, in fact.  and, yes, as i mentioned, it is already set to startup on launch.  but it fails to complete the startup.

**Comment by N6REJ** [comment]
1.0.17 is not the latest just fyi

**Comment by N6REJ** [comment]
@iansebryk well, I just tried it and your right it doesn't start.  I don't get any errors, but it does show the service running in tskmgr.  Doesn't show in system tray and apache is not running however.. strange

**Comment by iansebryk** [comment]
double-checked and i am running 1.3.  i think you were thrown by the 
version number in the screenshot. :)  as i mentioned, this has been 
going on for a loooong time.  :)

Ian Sebryk

403.399.1039

------------------------------------------------------------------------


Confidentiality Warning: This e-mail, and any attachments thereto, is 
intended only for use by the addressee(s) named herein and contains 
legally privileged and/or confidential information. If you are not the 
intended recipient of this e-mail (or the person responsible for 
delivering this document to the intended recipient), you are hereby 
notified that any dissemination, distribution, printing or coping of 
this e-mail, and any attachment thereto, is strictly prohibited. The 
sender does not accept any responsibility for any loss, disruption or 
damage to your data or computer system that may occur while using data 
contained in, or transmitted with, this e-mail. If you have received 
this e-mail in error, please immediately notify us by return e-mail and 
permanently delete the original and any copy of any e-mail and printout 
thereof. Thank you.

**Comment by crazy-max** [comment]
Hi @iansebryk,

As i saw in your log `neard-startup.log` from line 158-187, you have the cause of the restart prompt.
You stop your computer without leaving Neard properly from system tray :

![image](https://user-images.githubusercontent.com/1951866/30609571-0ad6caba-9d7c-11e7-9ea7-4cdf005e71a4.png)

If you do not close Neard neatly, the services will remain installed after the computer restarts and will have to be reinstalled the next time Neard is run.

**Comment by iansebryk** [comment]
hm.  okay.  that's tedious...so i'll script it.  thanks!
