### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#336]
Max, can we get composer & possibly grunt built in?

**Comment by crazy-max** [comment]
Hi @N6REJ, Composer is already available as a module and [Grunt can be installed](https://gruntjs.com/getting-started) with npm (node.js) through a package.json in your project for example.

**Comment by N6REJ** [comment]
@crazy-max am I doing something wrong?
![image](https://user-images.githubusercontent.com/1850089/32812865-d78e1fec-c96c-11e7-855b-9c9c84ed097a.png)

**Comment by crazy-max** [comment]
It seems to be a permission issue like here : https://stackoverflow.com/questions/22325031/npm-please-try-using-this-command-again-as-root-administrator

Try :
* npm cache clean -f
* Check if the folder `neard\tmp\npm-cache` exists

Seems also linked to your issue with MySQL and permission if neard is put in C:\

**Comment by crazy-max** [comment]
Hum it seems to be the same issue : https://stackoverflow.com/questions/22325031/npm-please-try-using-this-command-again-as-root-administrator

Try :
* `npm cache clean -f`
* Check if folder `neard\tmp\npm-cache` exists.

Also it seems to be related to your MySQL problem when neard is put in C:\
