### ISSUE TITLE
do npm tool installs become portable too?

### ISSUE THREAD

**Issue by iansebryk** [crazy-max/neard#338]
forgive me is this is a stupid question, but i'm curious to know.  i am wanting to install Gulp, Grunt and a couple other npm tools and, as they are npm installations, i was curious if they installed to the NodeJS folder and became part of the Neardly World of Portableness [NWoP] (which would be so awesome i could cry...) or if it did something else and became part of the OS's file system...

**Comment by N6REJ** [comment]
I was wondering the same

**Comment by crazy-max** [comment]
Hi,

You can install npm packages [globally](https://docs.npmjs.com/getting-started/installing-npm-packages-globally) with the flag `-g`.

For example : `npm install -g gulp` and then `gulp` will be available for the whole system as it will be in PATH (`neard\bin\nodejs\nodejsx.x.x\gulp.cmd`)
