### ISSUE TITLE
Deprecate php3

### ISSUE THREAD

**Issue by N6REJ** [crazy-max/neard#340]
I'm fairly sure we can deprecate .php3 from apache.
`AddType application/x-httpd-php .php3`

**Comment by crazy-max** [comment]
Hi @N6REJ, when php3 first got released, developpers decided to use the php3 extension but it has been dropped since php 4. This type is here for backward compatibility and does not affect Apache. So i will keep it for the moment ;)

**Comment by N6REJ** [comment]
I understand, I just figured since we are at a minimum of php5 it would make sense.
