### ISSUE TITLE
Code source of neard.exe

### ISSUE THREAD

**Issue by zoubir-saidi** [crazy-max/neard#76]
Hello,
I don't know if neard is under GPL licence ( I hope so !)
Could you  please publish the source code  of neard.exe ,

**Comment by blaisexen** [comment]
because of this project I earn $900, I used it as an installer for customized wamp. lol, I get a lot from this, I wonder why this was free!  I guess the owner has much money! thank you!  I like open source code, the owner gets nothing, the user's get a lot. lol
