### ISSUE TITLE
Apache Crashes at or after Filezilla loads!

### ISSUE THREAD

**Issue by CoZmicShReddeR** [crazy-max/neard#77]
Apache Crashes at or after Filezilla loads!

Windows Server 2008 64-Bit
https://www.sendspace.com/file/8zw461

**Comment by crazy-max** [comment]
Some feedback @CoZmicShReddeR ?

**Comment by Jeffjeffjeffjeff** [comment]
Hello,

Same problem here, but with Windows 7. Neard 1.0.12.
![image641](https://cloud.githubusercontent.com/assets/11990554/7197833/0f5c9476-e4e6-11e4-897e-6026a45f7f1a.png)

And if I try to open Neard from a fresh folder in another disk, I have this one:
![image454562](https://cloud.githubusercontent.com/assets/11990554/7197849/2eb267f6-e4e6-11e4-9288-f3ec092dbb30.png)

I don't know if I can do your command suggestion.

Merci!

**Comment by Jeffjeffjeffjeff** [comment]
More information:

The Apache crash happen on this message in the loading window: Start Filezilla 0.9.47 (neardfilezilla) service...

Also, I have to open Neard twice, because the first launch crash the app after some loading, without error message. Apache crash happen on the second launch.

**Comment by Jeffjeffjeffjeff** [comment]
And if I try to "Start Apache sevice" directly from the app, I have this one:

![image56456](https://cloud.githubusercontent.com/assets/11990554/7198069/a5ea2bae-e4e8-11e4-9881-d02e35f6c558.png)

**Comment by Jeffjeffjeffjeff** [comment]
Actually, apache folders in Neard was just almost full empty...This is why there is all this error message I suppose.
And "Install service" doesn't work. So, I've installed Apache from there: http://archive.apache.org/dist/httpd/binaries/win32/
- Copy / paste what is in the apache 2.2.22 folder (from the fresh install) to the Neard Apache 2.2.22 Folder.

It work, but this is not the best solution... that sucks I've losed the cool Index page from Neard.

Any suggestion..?

Thanks!

**Comment by Jeffjeffjeffjeff** [comment]
More news, again... :dancers: 

If I copy the "conf" folder from the apache 2.2.22 from the Neard .zip, and paste to the same folder on my working Neard, and start it... I have this one, and apache doesn't start:

![image6546545](https://cloud.githubusercontent.com/assets/11990554/7198423/72aee30c-e4ec-11e4-995a-dce016f873fb.png)

Well, this is clearly not the best solution to manually install apache in Neard.
Any suggestions?

**Comment by Jeffjeffjeffjeff** [comment]
So, to summarize, when I launch a new Neard folder, the real problem is that nothing is installed. This is the main problem.

![image1354654](https://cloud.githubusercontent.com/assets/11990554/7198745/73c2f708-e4ef-11e4-8bc0-255a8071648d.png)

I have killed every useless background process on my windows which can make conflict. And I have turned off every antivirus, firewall...

**Comment by Jeffjeffjeffjeff** [comment]
https://www.sendspace.com/file/6wo7xg

**Comment by crazy-max** [comment]
Ok @Jeffjeffjeffjeff i will check your issue

**Comment by Jeffjeffjeffjeff** [comment]
Thanks!

But I've found the solution actually. I've downloaded Neard from Github, and there is no executable anywere in any folder... Like /bin/httpd.exe. This is why the installation doesn't work.
So, if I download from Sourceforge, everything work well.

I met an other problem but it has already been mentioned: changing apache version require to manually change path in httpd.conf and httpd-ssl.conf, if the folder is not in c:/neard.
This is also complicated to select an other version of PHP. The path remains c:/neard.

Please, continue this awesome work! This is an fantastic software! My favorite on this kind.

**Comment by crazy-max** [comment]
Yes indeed the binaries are only available on Sourceforge.
Btw the issue #81 will be resolved soon ;)

**Comment by crazy-max** [comment]
And don't forget to read the [README.md](https://github.com/crazy-max/neard/blob/master/README.md) ;)
