### ISSUE TITLE
Add Composer in Neard tools

### ISSUE THREAD

**Issue by lothereus** [crazy-max/neard#80]
Should be a good idea no ?

**Comment by crazy-max** [comment]
Yes it should be a good idea but it's project specific.
I can implement for each project an automatic download of composer for example.

**Comment by lothereus** [comment]
Composer can be installed globaly, not only for each project (I use it directly in Neard cmd console since I installed it)... but having an option to install it for a specific project could be great ;-)

**Comment by crazy-max** [comment]
Solved on Neard 1.0.15
