### ISSUE TITLE
Installing Apache addon need manual configuration

### ISSUE THREAD

**Issue by lothereus** [crazy-max/neard#81]
While installing new Apache version you give, I had to modify some stuff in the httpd.conf because the install path was not correctly defined... "C:/neard" is default but I installed Neard on another drive.

The concerned lines : 37, 272, 273, 550, 559, 562, 565

Maybe it's possible to do that automatically when user active a new bin version ;-)

PS: same stuff to change in extra conf files used (i.e ssl, vhost)
PS2: same stuff for Php Addon with php.ini

**Comment by crazy-max** [comment]
Humm of cours the default path is ``C:/neard`` but when you start neard it will change the path automatically in the config file.
For this i use the file located in ``neard/core/resources/paths.dat``. This file adds the paths where you start neard. Do you C:/neard in this file ?

**Comment by lothereus** [comment]
No I have E:/Neard but at the start (when I charged the addon first time), It didn't change the path in the conf files. I had to change it manually. Since I changed it, it works well ^^

**Comment by crazy-max** [comment]
Solved on Neard 1.0.13
