### ISSUE TITLE
Error out of the box registry key

### ISSUE THREAD

**Issue by Panonc** [crazy-max/neard#84]
Hi,
I just downloaded neard, unziped it and launched neard.exe
I let you see the error:
![errorneard](https://cloud.githubusercontent.com/assets/11424580/6597214/34937032-c7fb-11e4-922f-88e5b101c640.png)

I don't know what is it and why.

**Comment by Panonc** [comment]
It may be because I don't own any rights on this computer ...

**Comment by crazy-max** [comment]
Yes it can be an admin rights problem.
Can you follow the steps for troobleshooting on the README.md please?

**Comment by crazy-max** [comment]
You need to have Administrators privileges to launch Neard
