### ISSUE TITLE
I get "Error setting NEARD_PATH registry key" when it sets up Filezilla

### ISSUE THREAD

**Issue by hmny** [crazy-max/neard#85]
here is the error:
![](http://i.imgur.com/AvlNhOw.png?1)
it is probably just an admin privilege related error in Windows (trying this in University so I don't have admin privileges).
Is there anyway to not boot Filezialla when nead starts?

**Comment by crazy-max** [comment]
Hi, in the neard.conf file you can set filezillaLaunchStartup to 0.

**Comment by hmny** [comment]
awesome! thanks

**Comment by crazy-max** [comment]
By the way, it seems you have insufficient rights to launch Neard like the issue #84
