### ISSUE TITLE
System Idle Process block services

### ISSUE THREAD

**Issue by Owned67** [crazy-max/neard#87]
Hello,

i have downladed archive neard-master, xtract and launch neard.exe

cd H:\Web\bin\apache\apache2.2.22

H:\Web\bin\apache\apache2.2.22\bin>httpd.exe -k install
Installing the Apache2.2 service
The Apache2.2 service is successfully installed.
Testing httpd.conf....
Errors reported here must be corrected before the service can be started.
httpd.exe: Syntax error on line 85 of H:/Web/bin/apache/apache2.2.22/conf/httpd.
conf: Cannot load H:/Web/bin/apache/apache2.2.22/modules/mod_dav_svn.so into ser
ver: %1 n\x92est pas une application Win32 valide.

H:\Web\bin\apache\apache2.2.22\bin>httpd.exe -k start
httpd.exe: Syntax error on line 85 of H:/Web/bin/apache/apache2.2.22/conf/httpd.
conf: Cannot load H:/Web/bin/apache/apache2.2.22/modules/mod_dav_svn.so into ser
ver: %1 n\x92est pas une application Win32 valide.

**Comment by crazy-max** [comment]
Hi,

Check your vcruntimes.
You can download and install this pack: http://sourceforge.net/projects/neard/files/Tools/neard-vcredists-x86.exe/download

**Comment by Owned67** [comment]
Logs & tmp:
http://www.mediafire.com/download/0mkqxevka55v4ov/logs.7z

**Comment by Owned67** [comment]
Hello,

so, i have removed neard, i downloaded 1.0.13.

Extract and launch neard.exe, service don't start...

Logs & tmp:
http://www.mediafire.com/download/kxybxavtvb8yaj2/logs.rar

**Comment by crazy-max** [comment]
Hi!

Ok i will check your logs.

Thanks

**Comment by crazy-max** [comment]
![pas de nom](https://cloud.githubusercontent.com/assets/1951866/7970026/838be962-0a3b-11e5-9842-603fbb046df1.jpg)

I have upload your screenshot on this issue.

Please try these steps :

* Install the latest vcruntimes
The link : http://sourceforge.net/projects/neard/files/Tools/neard-vcredists-x86.exe/download

* Disable http.sys
- Press WINDOWS + R
- Enter regedit
- Go to: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP
- Add a new DWORD (32-bit) value
- Name it ‘NoRun’ not including the quotes
- Double click the new property
- In the Value data field type ‘1’ not including quotes and click OK
- Reboot your computer

* You may have a malware on your computer
Download an malware remover like Spybot: https://www.safer-networking.org/fr/mirrors16/

**Comment by Owned67** [comment]
vcruntime is already installed.

http is disabled

no malware (malware byte premium)

restart pc and same problem...

**Comment by crazy-max** [comment]
Ok i think the problem came from this command :

``NETSTAT -aon | FIND ":80" | FIND "LISTENING"``

Can you type this command in your cmd and send me a screenshot ?

Thanks

**Comment by Owned67** [comment]
NETSTAT -aon | FIND ":80" | FIND "LISTENING"
FINDFIND::  ':80''LISTENING': :

 No such file or directory No such file or directory

I use cygwin.

**Comment by crazy-max** [comment]
Ok thanks i will resolve this issue asap.

**Comment by crazy-max** [comment]
Solved on Neard 1.0.13
