### ISSUE TITLE
Neard 1.0.14

### ISSUE THREAD

**Issue by Owned67** [crazy-max/neard#90]
Hello,

le service Apache 2.2.22 (neardapache) ne peut être installé : impossible de démarrer le service: Erreur statut 1 (1: the service is not running.)

H:\Web\bin\apache\apache2.2.22\bin>httpd.exe -k install
[Wed Jun 10 10:58:04 2015] [error] Apache2.2: Service is already installed.

(OS 10048)Une seule utilisation de chaque adresse de socket (protocole/adresse r
Úseau/port) est habituellement autorisÚe.  : make_sock: could not bind to addres
s [::]:443
(OS 10048)Une seule utilisation de chaque adresse de socket (protocole/adresse r
Úseau/port) est habituellement autorisÚe.  : make_sock: could not bind to addres
s 0.0.0.0:443
no listening sockets available, shutting down
Unable to open logs

Logs:
http://www.mediafire.com/download/kxybxavtvb8yaj2/logs.rar

**Comment by crazy-max** [comment]
It seems that you have an Apache instance already launched.
Check others installations like Wamp, Xampp are not launched before starts Neard.

**Comment by Owned67** [comment]
Aucune instance n'est lancé, le port 80 et 443 ne sont pas utilisé

**Comment by crazy-max** [comment]
Ah oui en effet Apache ne peut pas se lancer à cause d'un processus en écoute sur le port 443.
Un pid est forcément lié à un processus, pouvez-vous entrer cette commande pour ressortir le nom de processus :

``tasklist /v /fi "PID eq 2552"``

Remplacer 2552 par PID du processus courant utilisant le port.

PS : Si vous voulez désactiver le SSL pour démarrer Apache, ouvrir le fichier ``neard\bin\apache\apache2.2.22\conf\httpd.conf`` et mettre un ``#`` devant la ligne ``Include conf/extra/httpd-ssl.conf``

**Comment by Owned67** [comment]
C'est regrettable qu'on doit installer les rutimes à chaque fois, j'ai redémarré le PC et tout démarre correctement.

Merci pour votre aide cependant je vais retourner sous wampp qui st plus rapide au lancement...

Cordialement,
