### ISSUE TITLE
Filezilla conflict

### ISSUE THREAD

**Issue by misuv** [crazy-max/neard#92]
If I have Filezilla server already installed on port 21 nerdfilezilla service cannot be installed.

**Comment by misuv** [comment]
Solved, port can be changed after nerd start, but you have to reinstall FileZilla service

**Comment by crazy-max** [comment]
Indeed Filezilla service need to be restarted on port change.

**Comment by misuv** [comment]
Thanks. Solved


Spor la lucru
Mihai Visan
0740.018.021
