### ISSUE TITLE
Taskbar icon on Windows 10

### ISSUE THREAD

**Issue by misuv** [crazy-max/neard#93]
On Windows 10 the taskbar icon it does not appear at sistem restart.

Services are running, but no icon. (Correct settings for taskbar icons are applied)

**Comment by crazy-max** [comment]
Hi,

Are you sure services are running on windows startup ?
You have checked "launch at startup" option on Neard (check Neard shortcut in startup folder) ?
UAC enabled ?

**Comment by misuv** [comment]
Hi

1. launch at statup option on Neard is checked
2. neard service on startup is enabled in windows
3. all neard services (apache, mysql...) I had to manualy changed them from manual to automatic start 
even if launch on start option was checked
4. neard icon is not shown on taksbar even settings are that all icons to be shown
5. system is Windows 10 with fresh install
6. UAC is disabled
7. neard is started as administrator
8. all changes are made as administrator


problems:
1. services are running, but neard icon is not shown in taskbar
2. if I don’t set manualy the services to start automatic, even if launch on start option was checked they remain on manual

Mihai
PS the neard update file on Git is missing, so in order to update I have to reinstall all DB. And that is frustrating.

**Comment by crazy-max** [comment]
If you start neard by launch the exe directly you have the systray icon ?
I think the problem occurs only on launch on startup option. I will check that issue on a VM.

And i have plan to build an InnoSetup for further releases ;)

**Comment by misuv** [comment]
On manual start of exe I have systray icon.

Mihai

**Comment by crazy-max** [comment]
Ok fixed, will be available in the next release.

**Comment by crazy-max** [comment]
Solved on Neard 1.0.16
