### ISSUE TITLE
port 80 is already used  (Windows 10 / Neard 1.0.14)

### ISSUE THREAD

**Issue by bgva2005** [crazy-max/neard#94]
HI, please with your help:
When I start Neard, Apache doesn't installed, I have this error message :

Apache 2.2.22 (neardapache) service cannot be installed: -Port 80 is used by an other application.

I don´t have wampapache

C:\WINDOWS\system32>netstat -an | find ":80" | find "LISTENING"
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING
  TCP    0.0.0.0:8092           0.0.0.0:0              LISTENING
  TCP    [::]:80                [::]:0                 LISTENING
  TCP    [::]:8092              [::]:0                 LISTENING

There is no process called httpd.exe

I changed successfully the port to: 8080 but when I tried to install a service I receive this message: Error during installation of Apache service.

**Comment by crazy-max** [comment]
Hi,

When Neard starts and display the port used error, open Neard in the systray, go to Apache and select Change port. Wait for service restarts.

**Comment by crazy-max** [comment]
Btw it seems a service on your computer uses port 80.

Check services and use ProcMon to find out which process uses it.

**Comment by crazy-max** [comment]
Some news @bgva2005 ?
