### ISSUE TITLE
Add Python tool

### ISSUE THREAD

**Issue by crazy-max** [crazy-max/neard#98]

**Comment by crazy-max** [comment]
@pedzed If you dont want Python on Neard you can easily remove it by delete the content of the python folder in `neard\tools\python\`

**Comment by pedzed** [comment]
> If you dont want Python

No, that's not it. I just wondered about what you meant with Python tool.

**Comment by crazy-max** [comment]
Python tool is in fact the binaries required for node-gyp for example.
It is based on https://winpython.github.io/
